### ISSUE TITLE
resource-timegrid plug-in unit Cannot be used under Vue

### ISSUE THREAD

**Issue by jekip** [fullcalendar/fullcalendar-vue#100]
### Bug Reports
vue npm below
fullcalendar/resource-timegrid 5.1 unable to install  specially install 5.0 ，fullcalendar are 5.1

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
