### ISSUE TITLE
Unable to load events from a computed property - Vue

### ISSUE THREAD

**Issue by astyltsvig** [fullcalendar/fullcalendar-vue#102]
### Bug Reports
https://codesandbox.io/s/eager-flower-wn0f5?file=/src/DemoApp.vue

As the sandbox indicates, you will not be able to load data from a computed property, it was possible in v4.

Any solution on that?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-vue/issues/96
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

As a workaround, you can supply the events as a function:

https://codesandbox.io/s/priceless-snow-f9xzg
