### ISSUE TITLE
UMD build and publish on CDN

### ISSUE THREAD

**Issue by iiibbbmmm** [fullcalendar/fullcalendar-vue#104]
### Feature Requests
I want a UMD build like V4, publishing it on CDNs would be better. 😀

**Comment by arshaw** [comment]
I'm actually thinking about outputting FC's packages to all three popular formats: ESM, CJS, and browser global. Hopefully that would achieve what you want. Here is a ticket for publishing to a browser-global file that could be used with a CDN:
https://github.com/fullcalendar/fullcalendar/issues/5617
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
