### ISSUE TITLE
Unable to import luxon plugin

### ISSUE THREAD

**Issue by rachitpant** [fullcalendar/fullcalendar-vue#106]
### Bug Reports
[Reproduced here](https://codesandbox.io/s/fullcalendar-v4-vue-1k4u5)

Unable to import luxon plugin into Vue component project.
Please see a forked project linked above.
I am able to use other FullCalendar plugins that I wanted in my project , but not the moment and luxon plugins.

**Comment by acerix** [comment]
The issue is that your demo is using version 4 but has version 5 of the luxon plugin, the versions need to match:

https://codesandbox.io/s/fullcalendar-v4-vue-08tnv
