### ISSUE TITLE
timeGrid.receiveContext is not a function

### ISSUE THREAD

**Issue by ashikvs** [fullcalendar/fullcalendar-vue#108]
i see this issue when i downloaded a creative template "https://demos.creative-tim.com/vue-material-dashboard-pro/#/dashboard", this bug shows up in colsole whenever i try to switch to day or week mode. month view works fine.
i am trying in my local machine

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
