### ISSUE TITLE
The eventContent slot doesn't properly destroy the Vue components inside

### ISSUE THREAD

**Issue by pietdevries94** [fullcalendar/fullcalendar-vue#111]
When an event gets removed, it doesn't destroy the content of the slot properly, which results in the destruction lifecycle hooks `beforeDestroy` and `destroyed` not triggering.

Reproduction: the following codesandbox has events. When you move away to a different month, or move an event around you get console logs for mounted, but not for destruction.

https://codesandbox.io/s/tender-nightingale-jrft3?file=/src/EventWithHooks.vue

**Comment by arshaw** [comment]
This is fixed in 5.4.0:
https://codesandbox.io/s/exciting-herschel-sjmzt?file=/src/EventWithHooks.vue
