### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by ankit-alpha-q** [fullcalendar/fullcalendar-vue#114]
Must use import to load ES Module: C:\Users\XYZ\Desktop\event\bitpodjs\node_modules\@fullcalendar\vue\dist\main.js require() of ES modules is not supported. require() of C:\Users\XYZ\Desktop\event\bitpodjs\node_modules\@fullcalendar\vue\dist\main.js from C:\Users\XYZ\Desktop\event\bitpodjs\node_modules\vue-server-renderer\build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename main.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\XYZ\Desktop\event\bitpodjs\node_modules\@fullcalendar\vue\package.json.

**Comment by dmitrijt9** [comment]
**@fullcalendar/vue version: 5.3.0
nuxtjs version: 2.14.1**

I can confirm the same error. The issue is quite strange. When navigating using vue router everything is fine. But after refreshing a page with calendar this error occurs:

> Must use import to load ES Module: /application/node_modules/@fullcalendar/vue/dist/main.js require() of ES modules is not 
> supported. require() of /application/node_modules/@fullcalendar/vue/dist/main.js from /application/node_modules/vue-server-
> renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which 
> defines all .js files in that package scope as ES modules. Instead rename main.js to end in .cjs, change the requiring code to use 
> import(), or remove "type": "module" from /application/node_modules/@fullcalendar/vue/package.json.

Please, any suggestions? Really, can't leave it like this in my application.

**Comment by ankit-alpha-q** [comment]
@dmitrijt9 
Add these to your nuxt.config.js,

  build: {
    transpile: /@fullcalendar.*/, // transpile ESM modules within all fullcalendar packages
  },


Working fine, 
If it does'nt try to start with a fresh branch,
- clean cache (npm/yarn clean cache)
- then add packages

**Comment by dmitrijt9** [comment]
@ankit-alpha-q Thanks a lot it helped.

Btw do you think its ok, that the package is not already prepared right? Even in documentation there are not mentions about it.

**Comment by ankit-alpha-q** [comment]
@dmitrijt9 
This fix is save and I have picked it from the official documentation for NUXT implementation of FullCalender.
You can check the nuxt.config.js file the link below,
https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/nuxt

**Comment by dmitrijt9** [comment]
@ankit-alpha-q 
Sure it's save :) I'm just curious why not to make commonjs version when publishing module. 
But nevermind. Again, thanks for help, didn't notice the example in docs :+1:

**Comment by acerix** [comment]
I believe this explains the issue:
https://github.com/fullcalendar/fullcalendar/issues/5393#issuecomment-667701320
↑
Please visit those issues, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
