### ISSUE TITLE
DayTimeGrid resetting scroll position when using validRange in options

### ISSUE THREAD

**Issue by AbrahamBrookes** [fullcalendar/fullcalendar-vue#115]
I have a pretty esoteric system here using Vue, Vuex, and namespaced modules. I thought that because I had such a complex system, this bug was far more complex than it actually was, so please excuse the over-engineered reconstruction here:
https://codesandbox.io/s/sad-shadow-zfj9g

**Instructions**
Scroll away from the initial time and then click the 'add event' button. Notice the calendars' scroll position resets.

After much hair pulling and head butting, it seems that my `options.validRange` property is causing the above behaviour. After reading the docs on it, I'm thinking `validRange` is irrelevant if you're only using the `dayTimeGrid` view?

In any case, this bug took me way too long to track down. I don't really know why it happens, but commenting out that property removed the unwanted behaviour. Is this something that needs fixing or am I using the property incorrectly?

**Comment by acerix** [comment]
`validRange` is to limit which dates the user can navigate to (eg. by clicking prev/next buttons) and so the start/end should only be a date like '2020-09-03'.

It's not clear why the scrolling reset in your demo, but using slotMinTime/slotMaxTime is the correct way to limit the visible hours, and it's working fine without that `validRange` setting.
