### ISSUE TITLE
Missing googleCalendarApiKey parameter

### ISSUE THREAD

**Issue by wydingez** [fullcalendar/fullcalendar-vue#12]
Hello, thank you for such a good plugin. I found that your vue version does not have the `googleCalendarApiKey` parameter when using the `@fullcalendar/google-calendar` plugin; 

I found that `INPUT_DEFS` is missing the definition of this parameter in the `fullcalendar-options.js` file. I hope that you can fix this problem as soon as possible, thank you:-D

**Comment by arshaw** [comment]
this option is now present in v4.1.1 !!!
