### ISSUE TITLE
`*Content` slots do not support dynamically imported components

### ISSUE THREAD

**Issue by paulyoung5** [fullcalendar/fullcalendar-vue#122]
If a Vue component passed to a FullCalendar slot is imported using a [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports), it's not used by FullCalendar; instead, the [fallback slot content](https://vuejs.org/v2/guide/components-slots.html#Fallback-Content) is used if available, failing that nothing is displayed.

I have ran into this for the `eventContent` and `resourceLabelContent` slots, and I'd guess this might apply to all `*Content` slots if they're implemented the same way.

Vue supports [dynamically imported](https://vuejs.org/v2/guide/components-dynamic-async.html) components such that they will only be downloaded at the point of render.

## Demo

Check out `DemoApp.vue` here:
https://codesandbox.io/s/demo-dynamically-imported-slot-content-bug-cz244

Note:

*  `FullCalendarResource` is imported statically and used by FullCalendar to render resources
*  `FullCalendarEvent` is imported dynamically and ignored by FullCalendar

### Expected behaviour

The `<full-calendar-event />` component placed within the `eventContent` slot should be used to render calendar events.

### Actual behaviour

Fallback slot content is used instead.

--

PS really enjoying that we can use slots now for resources and events, it's such a nice DX improvement so thanks for adding that!

**Comment by arshaw** [comment]
thanks, I will look into this for the next release.

the changes in this PR might potentially solve the problem: https://github.com/fullcalendar/fullcalendar-vue/pull/123

**Comment by arshaw** [comment]
I just released v5.4.0. Could you try reproducing and see if it's fixed?

I attempted [to write a test for this](https://github.com/fullcalendar/fullcalendar-vue/blob/v5.4.0/tests/main.js#L537) but it felt like it was failing for environment reasons. Not sure.

**Comment by paulyoung5** [comment]
thanks @arshaw, just tested with v5.4.0 in codesandbox though and it still seems to not use the imported event component 😿 (forked [here](https://codesandbox.io/s/demo-dynamically-imported-slot-content-bug-forked-553m7?file=/src/DemoApp.vue) using 5.4.0 incase you want a look)

**Comment by arshaw** [comment]
This has been fixed in [v6.0.0-beta.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.4)

Updated repro:
https://codesandbox.io/s/demo-dynamically-imported-slot-content-bug-forked-j0gd4w?file=/src/DemoApp.vue
(horizontally scroll until you see the event)

With v6, please ensure `@fullcalendar/core` and `@fullcalendar/resources` are installed as dependencies.

@paulyoung5, could you please confirm things are working?

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
