### ISSUE TITLE
Slot support for other content injection inputs

### ISSUE THREAD

**Issue by matthewsuan** [fullcalendar/fullcalendar-vue#126]
### Feature Requests
V5 brought some slot for `eventContent`. 
how can we add other slot types for `dayCellContent`, `dayHeaderContent` etc?

Ty

**Comment by nwbattlegrounds** [comment]
Definitely could use some slot options for things like the header toolbar, etc. The documentation on which v-slots are available feels a little lacking.

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)

**Comment by arshaw** [comment]
Actually, this isn't really a released feature.

I've improved the docs:
https://fullcalendar.io/docs/vue#slot-templates

All content-injection areas should work.

**Comment by alexcroox** [comment]
Does anyone have a list of the slots available, docs are pretty frustrating to jump around trying to find all instances of "xContent", especially when there is no search function in the docs...

**Comment by mmccallum** [comment]
> Does anyone have a list of the slots available, docs are pretty frustrating to jump around trying to find all instances of "xContent", especially when there is no search function in the docs...

Wouldn't that be helpful?  The docs do not list them.
