### ISSUE TITLE
.sync Modifier / v-model inside slot

### ISSUE THREAD

**Issue by Froxz** [fullcalendar/fullcalendar-vue#128]
Hi,

I think this is an addition to: 
[#105](https://github.com/fullcalendar/fullcalendar-vue/issues/105)
[#111](https://github.com/fullcalendar/fullcalendar-vue/issues/111)

Basically the .sync modifier or v-model is not updating the parent.

https://codesandbox.io/s/great-cori-fl25b

**Comment by acerix** [comment]
If I understand, you looking for ".sync Modifier" support for updating event properties?

https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

**Comment by Froxz** [comment]
Hi @acerix,

Yes, but it seems when used inside event slot is not synced between other events, and not updating the parent.

**Comment by Froxz** [comment]
Hi @acerix @arshaw 

Any plans to review VueJS reactivity inside slots soon?

**Comment by arshaw** [comment]
This has been fixed in [v6.0.0-beta.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.4)

Updated repro:
https://codesandbox.io/s/jovial-grothendieck-k1t9n1?file=/package.json

@Froxz , could you please confirm?

**Comment by Froxz** [comment]
Hi @arshaw I will try to check (can't promise)

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
