### ISSUE TITLE
All events re-render when updating event array

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-vue#129]
I'm not entirely sure whether this is a known limitation or a bug (and if so, whether it is with the vue connector or core), but here goes:

When providing events as an array, and then adding an event to that array, I would expect the old events not to re-render with the introduction of the virtual DOM in v5, similarly to how it behaves when calling `api.addEvent`. Currently that's not the case, reproduction here: https://codesandbox.io/s/sharp-margulis-xds32?file=/src/DemoApp.vue

So, assuming my events are provided through an array that is updated whenever events are added, removed or changed, how would I pass that to Fullcalendar while minimizing re-renders?

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3003
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
