### ISSUE TITLE
eventAllow VUE events not working

### ISSUE THREAD

**Issue by dbeyzad** [fullcalendar/fullcalendar-vue#136]
eventAllow vue events not worknig.

Due to missing from 

var EMISSION_NAMES = ['windowResize', 'dateClick', 'eventClick','eventAllow','eventMouseEnter', 'eventMouseLeave', 'select', 'unselect', 'loading', 'eventPositioned', '_eventsPositioned', 'eventDragStart', 'eventDragStop', 'eventDrop', 'eventResizeStart', 'eventResizeStop', 'eventResize', 'drop', 'eventReceive', 'eventLeave', '_destroyed', // should now be props... (TODO: eventually remove)
  'datesRender', 'datesDestroy', 'dayRender', 'eventRender', 'eventDestroy', 'viewSkeletonRender', 'viewSkeletonDestroy', 'resourceRender'];

Once I have added as above now works

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
