### ISSUE TITLE
Slot Support (feature request)

### ISSUE THREAD

**Issue by gongon2dotcom** [fullcalendar/fullcalendar-vue#14]
Is there any _Vue slot_ functionality support?

Thanks in advance.

**Comment by rangermeier** [comment]
It would be neat if one could use slots to render events.

I really would love to be able to do something like this:
```
<FullCalendar
  :events="events"
>
<template v-slot:event="{event, view}">
   <div class="my-calendar-event">{{ event.title }}</div>
</template>
</FullCalendar>
```

**Comment by irongomme** [comment]
I'm also intereted in !

This would let us customize some elements, like toolbar for exemple

**Comment by gongon2dotcom** [comment]
Nothing new? Is support planned for this feature?
It would be useful to have the possibility to specify slots for header or footer calendar.

Thanks!

**Comment by zintj** [comment]
I'm currently needing to completely change how an event looks and it's proving to be quite clunky at the moment. Being able to use a slot for this would be wonderful.

**Comment by Froxz** [comment]
Would be very nice having `slot` inside event, currently manually adding/removing `Vue Component` in a very dirty [solution](https://stackoverflow.com/questions/59356674/vue-fullcalendar-eventrender-add-vue-component/59375113#59375113). in `eventRender` and `eventDestroy`

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by brurubio** [comment]
Events Slots will be so helpful, exactly what I need. Do you have an idea when the v5 will be released?

**Comment by arshaw** [comment]
scoped slots are implemented in [the latest v5 beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

changelog: https://fullcalendar.io/docs/v5/upgrading-from-v4#vue-connector
example code: https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/vue/src/DemoApp.vue#L13

they can be used for any of the new *Content settings, not just for events.

**Comment by ssyberg** [comment]
> 
> 
> scoped slots are implemented in [the latest v5 beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)
> 
> changelog: https://fullcalendar.io/docs/v5/upgrading-from-v4#vue-connector
> example code: https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/vue/src/DemoApp.vue#L13
> 
> they can be used for any of the new *Content settings, not just for events.

the example code link appears to be broken

**Comment by arshaw** [comment]
sorry. moved to master: https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/vue/src/DemoApp.vue

**Comment by ssyberg** [comment]
> sorry. moved to master: https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/vue/src/DemoApp.vue

Thanks!

I noticed in the changelog that slots are available "with any of the *Content options in the API." Are these listen anywhere? I've tried searching through the API a bit but have only found eventContent. Is there one for toolbar?

**Comment by AbrahamBrookes** [comment]
It seems that using the new slot feature breaks reference to my root vue app? I have a component that sits inside the `eventContent` slot, and I can no longer access my root vue instance (in particular, my vuex store) from that component:

```

		<full-calendar 
			:options="calOptions"
		>
			<template v-slot:eventContent="event" >
				<planner-period
					:event="event"
				></planner-period>
			</template>

		</full-calendar>
```

Inside the `planner-period` component when I try to access my store data using `this.$store.state` I get `this.$store is undefined`. Is the calendar creating its own entirely new vue app?

**Comment by arshaw** [comment]
This has officially been release in v5: https://fullcalendar.io/blog/2020/06/v5-official

@AbrahamBrookes I moved your report to a new ticket: https://github.com/fullcalendar/fullcalendar-vue/issues/105

**Comment by arshaw** [comment]
@ssyberg , if you browse the docs in the "table of content" view: https://fullcalendar.io/docs#toc

...you'll be able to text-search for "Content" and you'll see

**Comment by Herz3h** [comment]
Is there only one slot ?

**Comment by alex-maereanu** [comment]
Yea.. not clear.

**Comment by OleksiyyRiabiy** [comment]
Guys, when I use scoped slots to customize an event the Calendar slows down. For example, changing the view is taking about 5 sec as well as moreLinkClick function or other actions with the Calendar. (Without slots the delay gets down to about 0.5 sec) Can you please check this out?

**Comment by keygun-development** [comment]
I'm missing a slot for the full event to be changeable (not only the content). I'm trying to open a custom made modal, but the only slot to be used is the `eventContent` slot. 

I'd like to see a _new slot_ or _component_ within the `<FullCalendar />`

Something like:
```
    <FullCalendar>
        <template #event="arg">
            <div class="flex w-full" :id="arg.event.id" @click="openModal(arg.event.id)">
                <p class="font-bold">
                    {{ arg.timeText }}
                </p>
                <p class="ml-2">
                    {{ arg.event.title }}
                </p>
            </div>
        </template>
    </FullCalendar>
```
