### ISSUE TITLE
#eventContent slot is not reactive to props, data, or v-model bindings

### ISSUE THREAD

**Issue by FeistyMango** [fullcalendar/fullcalendar-vue#141]
### Problem

Any bindings defined within the `#eventContent` slot are not reactive. I observed this with v-model bindings, props, and data bindings. They do not react to changes to data that they are bound against. I've confirmed that if I move the problem code outside of the `<FullCalendar />`, reactivity will function as expected.

See a reproducible example here using props - https://codesandbox.io/s/sleepy-shamir-31jx1?file=/src/DemoApp.vue
In this stripped-down example, state mutations of the data field `isVisible`  are not observed within the `eventContent` slot. Notice that if you default the initial value to true, you will see it render properly though.

### Related to 

#127 
#128

**Comment by FeistyMango** [comment]
I should note that if I change the event data intially passed into the `<FullCalendar />` `options` prop, the watchers configured underneath will properly react and rerender the entire calendar. However, this has very limited usability for customizable content within the `#eventContent` slot and performance implications since the entire calendar is being re-rendered rather than the events that change.

**Comment by maico910** [comment]
have any update about this? I want to use v5 for new features but I need to back to v4 about this issue

**Comment by arshaw** [comment]
This has been fixed in [v6.0.0-beta.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.4)

Updated repro:
https://codesandbox.io/s/jovial-proskuriakova-h1ph1k?file=/package.json

@FeistyMango and @maico910, could you please confirm?

**Comment by arshaw** [comment]
Released in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
