### ISSUE TITLE
Laravel wrong height calculation

### ISSUE THREAD

**Issue by Dzemy** [fullcalendar/fullcalendar-vue#144]
### Bug Reports
Here is new clear Laravel 7 project with @fullcalendar/vue, there is just one view with simple calendar. 
When you refresh the site multiple times the height in <div class="fc-view-harness fc-view-harness-active" ...> may be miscalculated. 

I noticed it just after shipping bcs you must have composer depe installed in --no-dev . The npm setting has no effect.

So just run `composer i --no-dev` host laravel and try refresh site multiple times.

I try it on my pc and server so I hope you can reproduce it.

#### The repro project
https://github.com/Dzemy/laraFcRepro

![image](https://user-images.githubusercontent.com/21079305/104822196-172ee580-5841-11eb-9d5f-88006d03cf83.png)

![image](https://user-images.githubusercontent.com/21079305/104822211-26159800-5841-11eb-986a-d14f8abbdafa.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
