### ISSUE TITLE
Cannot bind model to :events, does not react

### ISSUE THREAD

**Issue by aldeng11** [fullcalendar/fullcalendar-vue#145]
Hi, I see various issues around bound models failing to react, but the workaround of embedding a fetch method in the computed property doesn't make sense for my application.

My app is an rrule editor, where you edit the rrule and the resulting events appear in the calendar.  The events are already there.  There's nothing to fetch.  I'm just editing the model.

v4 reacts when you bind a model to FullCalendar: https://codesandbox.io/s/fullcalendar-v4-vue-forked-fevn8?file=/src/DemoApp.vue

In v5, not only can I not get it to react, but it won't initialize with the bound model, either: https://codesandbox.io/s/charming-jepsen-293zv?file=/src/DemoApp.vue

I hope there's something I'm doing wrong.  Reacting to a bound model is pretty much the most fundamental part of Vue.  Maybe there's a cleaner workaround, at least?

**Comment by acerix** [comment]
I'm not very familiar wit Vue, but it does seem like a bug since the same worked in v4 and it looks correct to me.

**Comment by chanlito** [comment]
Yup, I facing this same issue as well.

**Comment by laurensiusadi** [comment]
@aldeng11 the codesandbox for v4 got errors, I can't run it.

**Comment by arshaw** [comment]
In v5, there's no `:events` prop. Everything needs to be put under the `:options` prop. Please see the docs: https://fullcalendar.io/docs/vue

**Comment by aldeng11** [comment]
The issue here is that the model doesn't react.  Can you post a codepen that illustrates model reaction?  The example in the docs is not about reaction.

Make an event that displays in the calendar.  Change its title in the bound options.events object.  The calendar should auto-update the title.  Any edit to that object needs to be immediately reflected in the UI.
