### ISSUE TITLE
FullCalendar VDOM already loaded

### ISSUE THREAD

**Issue by masonmonu** [fullcalendar/fullcalendar-vue#147]
Hi Team, 

_First of all thanks for creating Fullcalendar package in vue js. it works really fine._

> I am getting multiple warning in browser console which says 'FullCalendar VDOM already loaded'. I even don't registered FullCalendar as global component. Please suggest why it is happening and how it should be prevented.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ZoreAnkit** [comment]
In my case I have 2 fullcalendars in my project for diff modules namely -> Planning tool & Working hours


![Selection_065](https://user-images.githubusercontent.com/46300882/148069826-c3f4b0bd-62a2-4d73-9070-3c2a26c3105d.png)


![Selection_066](https://user-images.githubusercontent.com/46300882/148069889-8b447663-8d68-499f-856b-43a1b24314cc.png)

How do I implement above senerio?
