### ISSUE TITLE
Events add change doesn't render instantly

### ISSUE THREAD

**Issue by laurensiusadi** [fullcalendar/fullcalendar-vue#149]
https://user-images.githubusercontent.com/5661040/110904160-214dfb80-833b-11eb-8dbf-03669c3c5953.mp4

This issue happen on week and day view not on month view.
Happen on my setup, repeatable on https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue-vuex
Issue not found on both Vue codesandbox and fullcalendar core.

Steps:
1. Change view to week view
2. Drag select to open add event dialog
3. Press cancel
4. The empty selection stays, then click with mouse it disappears
5. Drag select to open add event dialog
6. Type in title, press OK to save
7. Event item stays empty, then when clicked it updates

**Comment by laurensiusadi** [comment]
OMG silly me.

After watching the code differences closely, found this:
```
calendarApi.unselect() // clear date selection
```
https://github.com/fullcalendar/fullcalendar-example-projects/blob/72136a72245bd0401670f546644d1fa2ae25f886/vue/src/DemoApp.vue#L57

Now the vuex example works as expected with that added.

But is this the intended behavior?

**Comment by acerix** [comment]
Yes, the selection needs to be cleared with `unselect`.

If there is still an issue, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
