### ISSUE TITLE
can't change firstDay

### ISSUE THREAD

**Issue by insology** [fullcalendar/fullcalendar-vue#15]
Hello,
adding the propos
firstDay="1"
`<FullCalendar 
		defaultView="timeGridWeek"
		:plugins="calendarPlugins"
		:events="events"
		minTime= "07:00:00"
		maxTime= "22:00:00"
		firstDay="1"
		locale="it"
		/>`
the day still on sunday.
I Also see a partial translation for IT, the labels all-day and today are in english

Thank you

MM

**Comment by insology** [comment]
![Schermata 2019-05-02 alle 18 10 13](https://user-images.githubusercontent.com/3527474/57090105-51bbbc00-6d06-11e9-8649-b73ed0e676f6.png)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mediaessenz** [comment]
firstDay has to be a number, but you entered a string.
Changing firstDay="1" to :firstDay="1" will do the job.

**Comment by insology** [comment]
:firstDay="1" works fine
