### ISSUE TITLE
ThemeSystem not working

### ISSUE THREAD

**Issue by alrisha** [fullcalendar/fullcalendar-vue#150]
I'm trying to use another theme, but if I set in config as ( this is an extract of my computed that composes all options object ... )
```
configOptions: function () {
      return {
        plugins: [timeGridPlugin, dayGridPlugin, bootstrapPlugin, interactionPlugin],
        locale: itLocale,
        allDaySlot: false,
        editable: true,
        selectable: true,
        height: 'auto',
        expandRows: true,
        themeSystem: 'spacelab'
      }
    },
```
I expect that theme should change as on [https://fullcalendar.io/demos] , but nothing changes.
I don't find a complete tutorial to set another theme as in this page
Maybe i haven't done all steps...

otherwise fullcalendar works correctly!

**Comment by acerix** [comment]
There is no "spacelab" theme, the only option is "bootstrap":

https://fullcalendar.io/docs/themeSystem
