### ISSUE TITLE
problems with Vite, ordering of import statements

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-vue#152]
To get the FullCalendar Vue plugin working with Vite's HMR, you'll need to import `@fullcalendar/core/vdom` for its side-effects before any other import. Example [from the docs](https://fullcalendar.io/docs/vue):

```js
import '@fullcalendar/core/vdom' // solves problem with Vite
import FullCalendar from '@fullcalendar/vue'
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction'
```

This configuration is recommended for other bundlers too, not just Vite, because it guarantees the ordering of import statements that FullCalendar internally needs. It prevents the JS error `Please import the top-level fullcalendar lib before attempting to import a plugin.`

The goal is to do away with this ordering requirement. See the following issue for more info: https://github.com/fullcalendar/fullcalendar/issues/6371

**Comment by Narven** [comment]
Man.. u are my 🦸‍♂️  today. I've just spent 4 hours trying to get vite to work fullcalendar with the issue:

`Please import the top-level fullcalendar lib before attempting to import a plugin.`

and that:

`import '@fullcalendar/core/vdom'`

just saved me another day of searching and punching my monitor. (my hands are hurting already)

Thanks 🙇

**Comment by Narven** [comment]
That really should be in the docs... somewhere... with huge spotlights and arrows pointing to it.

**Comment by AdrianMrn** [comment]
For anyone else using Vite to build a React application, you need to add this line instead: `import '@fullcalendar/react/dist/vdom';`

**Comment by Shikoruma** [comment]
This is working for 
`import dayGridPlugin from '@fullcalendar/daygrid'`
but not for 
`import timeGridPlugin from '@fullcalendar/timegrid'`

Any suggestion ?

**Comment by amine-elghazali** [comment]
I'm Trying to implement FullCalendar into my Nuxt3 project, But I keep getting an error that says : __vite_ssr_import_1__ is not defined

**Comment by castrix** [comment]
I just met this issue in `vite react`, and I just want to add that you can import the `@fullcalendar/core/vdom` in `app` level or `index` level. What I mean by that is that you don't need to import it in every file that import `@fullcalendar`, so you just need to import `@fullcalendar/core/vdom` once in your highest level file.

**Comment by damisparks** [comment]
Any suggestions on how to solve this? 
I am using vue3 with vite. 
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/28821368/181618621-ec8b005a-a27d-489a-8a78-120e2f1bb754.png">

**Comment by kcirefrz** [comment]
> For anyone else using Vite to build a React application, you need to add this line instead: `import '@fullcalendar/react/dist/vdom';`

You saved me!! ty

**Comment by dralucindaodonto** [comment]
For some unknown reason, if I import fullcalencar/vue3  in my vue3 + vite + typescript project, all the components becomes red on visual studio with the following error :  "any component name" cannot be used as a JSX component. / JSX element class does not support attributes because it does not have a 'props' property  / It complains many other things to.  I know for sure it is related to importing vuecalendar3. How can I fix this ? regards.

**Comment by hkc512** [comment]
> For some unknown reason, if I import fullcalencar/vue3 in my vue3 + vite + typescript project, all the components becomes red on visual studio with the following error : "any component name" cannot be used as a JSX component. / JSX element class does not support attributes because it does not have a 'props' property / It complains many other things to. I know for sure it is related to importing vuecalendar3. How can I fix this ? regards.

i having this error after import fullcalendar too

**Comment by techpool** [comment]
Anything to solve this? I have the exact same issue!

**Comment by damisparks** [comment]
> > For some unknown reason, if I import fullcalencar/vue3 in my vue3 + vite + typescript project, all the components becomes red on visual studio with the following error : "any component name" cannot be used as a JSX component. / JSX element class does not support attributes because it does not have a 'props' property / It complains many other things to. I know for sure it is related to importing vuecalendar3. How can I fix this ? regards.
> 
> 
> 
> Anything to solve this? I have the exact same issue!

@techpool follow the suggestions on the thread and you are good to do.

**Comment by Steve-madlad** [comment]
> To get the FullCalendar Vue plugin working with Vite's HMR, you'll need to import `@fullcalendar/core/vdom` 

You are a life saver man! been racking my brain for solutions.

**Comment by jairo-ab** [comment]
I'm using the library in Vue version 2.7 + Vite. How can I make this work?

**Comment by subashdbc** [comment]
@jairo-ab 
Just import this on main.js file `import '@fullcalendar/core/vdom'` on the top level

It works as expected!

**Comment by GustavoMelloGit** [comment]
I am still getting this error on 6.1.10

**Comment by KNR1997** [comment]
Thanks bro. It saves my day
