### ISSUE TITLE
Cannot drag Draggable list events in all day row

### ISSUE THREAD

**Issue by leahfkd** [fullcalendar/fullcalendar-vue#159]
Recently the vue fullcalendar draggable list events suddenly cannot be drag in all day row. 
I notice this since Tuesday. I already tried different fullcalendar-vue version (5.9.0, 5.8.0,5.4.0) but I still get the same behavior
Here's a sample code replicating the problem
https://codesandbox.io/s/misty-cookies-v9950?file=/src/DemoApp.vue

If you drag any list events to all day, it won't work but will work in time row.

This video shows how it currently behaves.

https://user-images.githubusercontent.com/64578927/129241689-500e896c-859e-43c4-8f6c-5d3701bc3507.mp4

And this video showing the expected behavior. It works in fullcalendar core.

https://user-images.githubusercontent.com/64578927/129242558-769b9de5-43f9-492e-bcb0-7945b5ab005a.mp4

**Comment by acerix** [comment]
It can't be set as "all-day" with a duration of 4 hours, it works by removing the duration:

https://codesandbox.io/s/nostalgic-fast-62t1v
