### ISSUE TITLE
Cannot resize event in month view

### ISSUE THREAD

**Issue by laurensiusadi** [fullcalendar/fullcalendar-vue#16]
Codesandbox: https://codesandbox.io/s/z2ovp94z0x

Resize working in week view:
![2019-05-04_10-24-16](https://user-images.githubusercontent.com/5661040/57173233-dddcf900-6e56-11e9-90c4-7c21b09d3a80.gif)

Resize not working in month view:
![2019-05-04_10-24-38](https://user-images.githubusercontent.com/5661040/57173237-ec2b1500-6e56-11e9-91e2-fb2348f9b42f.gif)

**Comment by laurensiusadi** [comment]
Found the problem:
It doesn't have resizable handle
![firefox_2019-05-11_07-29-26](https://user-images.githubusercontent.com/5661040/57562631-9d353080-73be-11e9-98fa-aef70fbdfd7f.png)

Should be:
![firefox_2019-05-11_07-28-33](https://user-images.githubusercontent.com/5661040/57562630-9c040380-73be-11e9-9e80-9c9bc697a5a5.png)

**Comment by arshaw** [comment]
i believe the issue you're describing is actually a core issue:
https://github.com/fullcalendar/fullcalendar/issues/2441
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
