### ISSUE TITLE
UMD library

### ISSUE THREAD

**Issue by kss160992** [fullcalendar/fullcalendar-vue#166]
Hi

Is there a UMD version of the vue connector for single file component.

**Comment by arshaw** [comment]
Please see the dist files here: https://www.jsdelivr.com/package/npm/@fullcalendar/vue3?path=dist

We offer the following:

- cjs: main.cjs.js
- esm: main.js
- global: main.global.js

What are you having a problem with?

**Comment by arshaw** [comment]
Forgot to add: UMD is unnecessary if all bases are covered by the three formats I listed (except for AMD, which nobody uses anymore)
