### ISSUE TITLE
i found a bug in Timeline ,when set eventMaxStack.i have a demo address,help me please.

### ISSUE THREAD

**Issue by gipal** [fullcalendar/fullcalendar-vue#167]
you can run this. please open this address.
https://codepen.io/gipal-the-animator/pen/PojEvQL

![2](https://user-images.githubusercontent.com/29369046/133720249-39dca9df-bcbd-4c0a-843e-fedbe743fd8b.jpg)
![3](https://user-images.githubusercontent.com/29369046/133720253-e01cfd07-9c6b-4368-ace4-8678ee8e5bdf.jpg)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6543
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
