### ISSUE TITLE
JSX issue when using in Vue 3 with Typescript

### ISSUE THREAD

**Issue by MikesGlitch** [fullcalendar/fullcalendar-vue#173]
# Description
When using the vue3 package FullCalendar component (with typescript), VSCode comes up with the following error.
```` Property 'template' does not exist on type 'JSX.IntrinsicElements'.ts(2339) ````

![image](https://user-images.githubusercontent.com/5285928/147340932-0a5b5e12-e729-435b-8a8e-6af388c11438.png)

# Replication
Open the fullcalendar-example-projects repository - go to the **vue3-typescript** folder (https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue3-typescript)

Open it in VsCode

Observe on line 115 - **[vue3-typescript/src/Demo.vue](https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/vue3-typescript/src/Demo.vue)**
![image](https://user-images.githubusercontent.com/5285928/147341325-d45197b1-a033-4d19-8c8e-43cbc742a817.png)

I did a bit of digging and it worked by completely removing the typings file: @fullcalendar\vue3\dist\main.d.ts  I think it may be something that file is importing is causing the issue

**Comment by acerix** [comment]
I don't have any issue building this example, this sounds like an issue with VSCode.

**Comment by treighmawaka** [comment]
@MikesGlitch this might be an issue with the Volar extension, if you're using it. See #https://github.com/johnsoncodehk/volar/issues/552. I remember having to downgrade to `v0.27.26` because in later versions, "template virtual code is changed to JSX to improve generic component support" to quote the project owner.

**Comment by MikesGlitch** [comment]
@treighmawaka   Aha!  Thanks, makes sense.  That's annoying - almost everyone who uses Vue 3 and vscode will be using that extension.

Thanks, we should probably close this then.

**Comment by maukoese** [comment]
I have this same error. It comes from the preact dependency, with typings in the jsx.d.ts file.

Is there a way to disable this? Cause it throws errors for any unsupported attributes. see image below.

![Screen Shot 2022-05-07 at 8 30 27 AM](https://user-images.githubusercontent.com/14233942/167242003-f1467522-ac28-48c1-a717-f2f0e331cc71.png)

**Comment by jhoermann** [comment]
> I have this same error. It comes from the preact dependency, with typings in the jsx.d.ts file.
> 
> Is there a way to disable this? Cause it throws errors for any unsupported attributes. see image below.
> 
> ![Screen Shot 2022-05-07 at 8 30 27 AM](https://user-images.githubusercontent.com/14233942/167242003-f1467522-ac28-48c1-a717-f2f0e331cc71.png)

@maukoese See https://github.com/johnsoncodehk/volar/discussions/592#discussioncomment-2163786 to disable the `preact` typings.

**Comment by r-yongkuk** [comment]
I have this same problem in nuxt3
<img width="773" alt="스크린샷 2022-08-10 오후 12 17 06" src="https://user-images.githubusercontent.com/107015574/183803131-a047e9ce-f5c6-4c46-b1d1-e1e3060aeb1f.png">

**Comment by L-value** [comment]
so can you tell me how to fix this issue i try all methods but still not work

**Comment by tarwin** [comment]
I'm having a very similar issue with `vue-tsc --noEmit`. Seems to be a problem where, when adding FullCalendar it ends up causing React DOM problems.

I know this is not the exact same problem, but thought it may help to debug.

![image](https://github.com/fullcalendar/fullcalendar-vue/assets/646149/31ffbb4a-278d-4348-8d93-7f4a09c1e928)
