### ISSUE TITLE
Event change class between determinate hours

### ISSUE THREAD

**Issue by ViniciusPolegario** [fullcalendar/fullcalendar-vue#180]
**Bug Reports**

When the event date is between 23:00:01 and 23:59:59, the event loses class "fc-daygrid-dot-event" and gains classes  " fc-daygrid-block-event fc-h-event", changing its view. 

Expected behavior:
Should keep the class  "fc-daygrid-dot-event" regardless of the time

Here is the reproduction link
https://codesandbox.io/s/rj4oi4

**Comment by acerix** [comment]
That is how events are displayed when they span more than one day, and since the default length of events is 1 hour (`defaultTimedEventDuration`) any event starting after 23:00 will end in the next day.
