### ISSUE TITLE
Render `eventContent` in the context of the main Vue application

### ISSUE THREAD

**Issue by larrifax** [fullcalendar/fullcalendar-vue#182]
When rendering Vue components inside of `<template #eventContent></template>`, the Vue components aren't rendered within the main Vue application's context, but in a new Vue application created by the following function:
https://github.com/fullcalendar/fullcalendar-vue/blob/d203b0c693b08a62cccdeb47a38fc609d41205ed/src/custom-content-type.ts#L57-L76

Since the new Vue application isn't connected to the main Vue application in any way, information about e.g. plugins are lost.
This makes it it impossible to use e.g. `useI18n()` from `vue-i18n-next` within the rendered components, as the composable fails to find provided values set by the i18n-next plugin (which isn't loaded in the new Vue instance).

Please see the attached PR https://github.com/fullcalendar/fullcalendar-vue/pull/181 for a solution proposal that seems to work.

**Comment by arshaw** [comment]
Fixed in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
