### ISSUE TITLE
Importing fullcalendar component breaks type checking with vue-tsc

### ISSUE THREAD

**Issue by Razi91** [fullcalendar/fullcalendar-vue#188]
Adding fullcalendar to project breaks type checking with `vue-tsc`.

reproduction: Just create a new project (for example with Quasar), add fullcalendar and try to use it.

https://codesandbox.io/s/39twy1?file=/src/components/ExampleComponent.vue:506-541
Just removing those 2 lines makes the problem disappear.

test in terminal with `yarn vue-tsc --noEmit`

Probably it loads some of Preact global defines breaking vue-tsc configs.

**Comment by Razi91** [comment]
It seems to be `vue-tsc` problem and it's solved in version `1.0.0-alpha.0`.

**Comment by arshaw** [comment]
thanks @Razi91 . looks like vue-tsc now has a stable 1.0

**Comment by Gilbert5210** [comment]
example
`
export const fullCalRender = () => {
     return <FullCalendar options={calendarOptions.value} />
}
`

export show error

![image](https://github.com/fullcalendar/fullcalendar-vue/assets/17983736/0760d63d-21b0-4c51-9ec9-94e176d61364)

can you help me?
@acerix @arshaw

**Comment by Gilbert5210** [comment]
package info
`
"@fullcalendar/core": "^6.1.11",
"@fullcalendar/daygrid": "^6.1.11",
"@fullcalendar/interaction": "^6.1.11",
"@fullcalendar/vue3": "^6.1.11",
"vue-tsc": "^1.0.24",
"typescript": "^5.0.4",
"vite": "^4.5.0",
"vue": "^3.3.4"
`
