### ISSUE TITLE
Updating events

### ISSUE THREAD

**Issue by Reached** [fullcalendar/fullcalendar-vue#19]
Hi there,

First of all, awesome plugin!

I am trying to update events by filling out values in a modal, however when firing `this.$refs.updateEvent(this.editForm);` it throws an error telling my that `Uncaught TypeError: _this.$refs.calendar.getApi(...).updateEvent is not a function`. 

I also tried to update the events "manually" like I would normally with vue by just setting it's properties, however I have trouble getting the actual index of the event I am editing, thus the calendar won't re-render properly (the event disappears).

How do you handle event updates in the calendar?

Best regards, Casper.

**Comment by Reached** [comment]
To anyone else looking for this, updateEvent was removed in v4 of Fullcalendar, so instead you need to retrieve a date object and set the properties directly from there:

```
var event = calendar.getEventById('a');
event.setProp('title', 'new title');
event.setStart(yourDate);
event.setEnd(yourDate);
```

An example from my implementation:
```
const updatedEvent = this.calendarRef.getEventById(this.editForm.id);

updatedEvent.setProp('title', this.editForm.title);
updatedEvent.setStart(this.editForm.starts_at);
updatedEvent.setEnd(this.editForm.ends_at);
updatedEvent.setProp('resourceId', this.editForm.resourceId);
```

Hope it helps someone in the future!

**Comment by acerix** [comment]
If there is still an error, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
