### ISSUE TITLE
fullcalender not showing time correctly on daygrid view

### ISSUE THREAD

**Issue by jyotivarade** [fullcalendar/fullcalendar-vue#192]
using the latest fullcalender version 
    "@fullcalendar/core": "^5.11.3",
    "@fullcalendar/daygrid": "^5.11.3",
    "@fullcalendar/interaction": "^5.11.3",
    "@fullcalendar/timegrid": "^5.11.3",
    "@fullcalendar/vue": "^5.11.3",
also check with below version dependencies but same result
   "@fullcalendar/core": "^5.11.2",
    "@fullcalendar/daygrid": "^5.11.2",
    "@fullcalendar/interaction": "^5.11.2",
    "@fullcalendar/list": "^5.11.2",
    "@fullcalendar/timegrid": "^5.11.2",
    "@fullcalendar/vue": "^5.11.2",
I have added the event on fullcalender but it is showing wrong time on daygridview and also on weekgrid view 

![image](https://user-images.githubusercontent.com/50901499/207412026-a546def7-fc2b-4628-bfc6-ee34290cfeda.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
