### ISSUE TITLE
timelineDay view error

### ISSUE THREAD

**Issue by bulletbs** [fullcalendar/fullcalendar-vue#2]
I've a problem with **timelineDay** view while using this Vue component. (also timelineWeek)
At the same time there is no problem with **resourceTimelineDay** view. It works fine!
But i need view without resources.

My imports
`import FullCalendar from '@fullcalendar/vue'`
`import timeline from '@fullcalendar/timeline';`
`import resourceTimelinePlugin from '@fullcalendar/resource-timeline';`

My Plugins 
`calendarPlugins: [ resourceTimelinePlugin, timeline ],`

An error appear in console while using timelineDay view:

> [Vue warn]: Error in mounted hook: "Error: The FullCalendar view "timelineDay" does not exist. Make sure your plugins are loaded correctly."

What else i can try to fix it?
Thanks!

**Comment by bulletbs** [comment]
Couple of hours I spent to find what's wrong with my code.
But problem gone away after browser restart! 
**timelineDay** now works perfectly fine! =)

Sorry for disturbing.

**Comment by arshaw** [comment]
no problem 👍
