### ISSUE TITLE
Unable to create event with dragging on timeGridWeek

### ISSUE THREAD

**Issue by laurensiusadi** [fullcalendar/fullcalendar-vue#20]
Setup:
1. Use default codesandbox, set **editable**  and **selectable** props to true
2. Go to week view
3. Try dragging on empty space
4. Only blue selector appears, not event block

![2019-05-11_07-17-14](https://user-images.githubusercontent.com/5661040/57562437-d2d91a00-73bc-11e9-8838-5a3166278be6.gif)

Expected behaviour:
![2019-05-10_22-42-48](https://user-images.githubusercontent.com/5661040/57539727-4e16dd80-7375-11e9-8ad7-2df74b6c02e2.gif)
This on is using https://github.com/CroudTech/vue-fullcalendar v4.0.0-1

**Comment by Cragstar** [comment]
Having the same issue. Basically had to set the calendar to selectable and then once the drag has completed - show a popup with the selected time/date to fill in other details.
You could just auto create an event that covers the dragged select.

Odd that this behaviour was taken out?

**Comment by arshaw** [comment]
**vue-fullcalendar** is a different project. this is the issue tracker for the official fullcalendar-vue plugin by the original creators of fullcalendar.

**Comment by Cragstar** [comment]
Maybe so but that behaviour was available in full calendar. Hence why I've
raised it.

**Comment by arshaw** [comment]
you guys need to enable the `selectMirror` flag for this to happen
https://fullcalendar.io/docs/selectMirror

you might be confused because it was previously called `selectHelper`

**Comment by laurensiusadi** [comment]
@arshaw I mentioned vue-fullcalendar to demonstrate that using the repo I'm able to do that, but why when I'm using this repo, I'm unable to do that. I know that it's a different repo.

Thanks for the help!

**Comment by laurensiusadi** [comment]
@arshaw `selectMirror` only available in timeGrid, while month view is dayGrid, any chance I can make it work in month view?

**Comment by arshaw** [comment]
Unfortunately that has never been available. Here's the ticket for it:
https://github.com/fullcalendar/fullcalendar/issues/2581
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
