### ISSUE TITLE
How to change view?

### ISSUE THREAD

**Issue by laurensiusadi** [fullcalendar/fullcalendar-vue#21]
Is there any method available to change view like this?
`this.$refs.fullCalendar.changeView('dayGridMonth')`

**Comment by Reached** [comment]
this.$refs.fullCalendar.getApi().changeView('dayGridMonth'); should do it :)

**Comment by laurensiusadi** [comment]
@Reached thank you it works!

**Comment by idesignzone** [comment]
Using this in vue 2 I get:

Property 'getApi' does not exist on type 'Vue | Element | Vue[] | Element[]'.
