### ISSUE TITLE
Is there any way to custom event display ?

### ISSUE THREAD

**Issue by ncbinh98** [fullcalendar/fullcalendar-vue#22]
I need to custom the events display on the calendar, and add popover when I hover to event or click on it. For example, I need something like this.
`<Fullcalendar> 
<template slot="event" slot-scoped="{event}">
<popover>{{event.title}}</popover>
</template>
</Fullcalendar/>`
But now, I dont see any doc about it? Or I miss something ? And Instead of that way, is there any other to do that ? Please help me.
Thanks in advance.

**Comment by Reached** [comment]
Use the eventRender event and do it in there:

`<FullCalendar default-view="resourceTimelineMonth" 
ref="calendar" 
@eventRender="showPopup" 
/>`

``
`
methods: {
    showPopup(info) {
        const tooltip = new Tooltip(info.el, {
              title: info.event.title,
              placement: 'top',
              trigger: 'hover',
              container: 'body'
         });
    }
}

**Comment by ncbinh98** [comment]
> Use the eventRender event and do it in there:
> 
> `<FullCalendar @eventRender="showPopup" />`
> 
> ```
> methods: {
>     showPopup(info) {
>         const tooltip = new Tooltip(info.el, {
>               title: info.event.title,
>               placement: 'top',
>               trigger: 'hover',
>               container: 'body'
>          });
>     }
> }
> ```

Thanks for reply, Can u teach me how to implement tooltip into nuxtJS ? I search on google just receive something like v-tooltip component,... I dont know how to do something such: new Tooltip(info.el,..) like u.

**Comment by ncbinh98** [comment]
> Use the eventRender event and do it in there:
> 
> `<FullCalendar @eventRender="showPopup" />`
> 
> ```
> methods: {
>     showPopup(info) {
>         const tooltip = new Tooltip(info.el, {
>               title: info.event.title,
>               placement: 'top',
>               trigger: 'hover',
>               container: 'body'
>          });
>     }
> }
> ```

thank you, thank you, it's work.

**Comment by wang4978** [comment]
> Use the eventRender event and do it in there:
> 
> `<FullCalendar @eventRender="showPopup" />`
> 
> ```
> methods: {
>     showPopup(info) {
>         const tooltip = new Tooltip(info.el, {
>               title: info.event.title,
>               placement: 'top',
>               trigger: 'hover',
>               container: 'body'
>          });
>     }
> }
> ```

I used it, but got an error :
[Vue warn]: Error in v-on handler: "ReferenceError: Tooltip is not defined"
I don't known how to fix it

**Comment by wang4978** [comment]
> > Use the eventRender event and do it in there:
> > `<FullCalendar @eventRender="showPopup" />`
> > ```
> > methods: {
> >     showPopup(info) {
> >         const tooltip = new Tooltip(info.el, {
> >               title: info.event.title,
> >               placement: 'top',
> >               trigger: 'hover',
> >               container: 'body'
> >          });
> >     }
> > }
> > ```
> 
> thank you, thank you, it's work.

I used it ,but got error:
TypeError: _tooltip.Tooltip is not a constructor

My setps:
stps1:
npm install tooltip.js --save
step2:
<FullCalendar @eventRender="showPopup" />
step3:
methods: {
    showPopup(info) {
        const tooltip = new Tooltip(info.el, {
              title: info.event.title,
              placement: 'top',
              trigger: 'hover',
              container: 'body'
         });
    }
}

**Comment by MarcosViniciusCL** [comment]
Where is Tooltip?

**Comment by acidjazz** [comment]
Yes, where is this Tooltip included??
