### ISSUE TITLE
eventSources prop not working if bound to a function

### ISSUE THREAD

**Issue by danipardo** [fullcalendar/fullcalendar-vue#23]
My component has a method to fetch events, something like this:

 `async getEvents(start, end) {
}
 `

In order to fetch events from the server, at first I tried this:

 `<FullCalendar :events="getEvents()" `

But that doesn't seem a very good idea. Instead, it is easier to use event-sources prop, which sends a list of event sources. The problem is that this prop can only be bound to a local property or computed property, and it doesn't seem to work if its bout to a function, for example:

     <FullCalendar :event-sources="getEventSources()" ....></FullCalendar>

     export default {
        computed: {
	
       },
       methods: {
	
	 getEventSources(){
	    return [
		{
	            events(params) {
			console.log("fetching events " + JSON.stringify(params.start))
			return $this.getEvents(params.start, params.end)
                    },
                    color: '#1ABC9C',
		    
		}
            ]
	    
	},
	
	async getEvents(start, end) {
	    
	    }

the getEventSources() method here does not get called, but If I convert it to a computed property, then it works (but I then cannot call this.getEvents()). Is there any solution, or I'm approaching the problem in a wrong way?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

THAT BEING SAID, i think you need to write `<FullCalendar :events="getEvents"` instead

**Comment by danipardo** [comment]
Hi Adam, there it goes:

https://codesandbox.io/s/bknid

Note that eventSources() is the method, that, if moved as a computed property, it will be invoked.

PS: kudos for this -> https://fullcalendar.io/reduced-test-cases

**Comment by arshaw** [comment]
so you're saying that if you move `eventSources` to be a computed property, and specify the tag like this `<FullCalendar :events="getEvents"`, things **work**?

**Comment by danipardo** [comment]
Not exactly. You don't specify a :events property. The sample above just shows that if eventSources is a computed property (where you can also do console.log()), it gets called. But If it is a method, as it is in the sample, you won't see the console.log mesage in the console. Does it makes sense?

**Comment by arshaw** [comment]
okay makes sense. looks like there's a bug! will get this fixed for the next release

**Comment by arshaw** [comment]
I took a second look at this. I hope I'm not making us run around in circles here. But I realized your `event-sources` property is a method. it MUST be an array. OR, if can be a bound statement that generates an array.

I modified your example: https://codesandbox.io/s/fullcalendar-vue-rigwm

It does `<FullCalendar :event-sources="getEventSources()">` which calls the `getEventSources` method which generates the array. The `console.log` successfully gets called. Does that make sense?

**Comment by danipardo** [comment]
Yes, it does make sense. I've edited my original codesandbox snippet, and If I add parenthesis, then it works. Parenthesis dont seem to be required when using @click="" and stuff like that, which is weird, but I'll try to figure out the explanation. Thanks a lot, I guess we can close the ticket then.
