### ISSUE TITLE
how to listen header prev,next click events?

### ISSUE THREAD

**Issue by Clago** [fullcalendar/fullcalendar-vue#24]
events prop set a func can listen,but I don't know how to add events to the view.

**Comment by Clago** [comment]
listen datesRender.

**Comment by Clago** [comment]
don't use default header prev,next;
get html out and bind event just like this
```
<div class="fc-button-group" style="float:right;">
     <button @click="prev" type="button" class="fc-prev-button fc-button fc-button-primary" aria-label="prev"><span class="fc-icon fc-icon-chevron-left"></span></button>
     <button @click="next" type="button" class="fc-next-button fc-button fc-button-primary" aria-label="next"><span class="fc-icon fc-icon-chevron-right"></span></button>
   </div>
   <FullCalendar
     class='demo-app-calendar'
     ref="fullCalendar"
     defaultView="dayGridMonth"
     :header="{
        left:'',
        center: 'title',
        right: '',
      }"
     event-color="red"
     :plugins="calendarPlugins"
     :weekends="calendarWeekends"
     :locale="zhLocale"
     :events="events"
     @dateClick="handleDateClick"
   />
```

**Comment by raisonon** [comment]
This is possible and I put my answer on SO: https://stackoverflow.com/questions/56622852/next-and-previous-month-watcher-in-vue-fullcalendar?noredirect=1#comment99828700_56622852

**Comment by oliver661** [comment]
Listeing on `datesRender` will take the warning as `Use of datesRender as an event is deprecated. Please convert to a prop.` 💔

**Comment by bhaskar-nair2** [comment]
They should really not convert datesRender into a prop, as that would make no sense. Having it as an emit will help us listen to changes easily.

**Comment by oliver661** [comment]
> They should really not convert datesRender into a prop, as that would make no sense. Having it as an emit will help us listen to changes easily.

I finally made it as `:eventRender="v => onEventRender(v)"` which is meaningless.

**Comment by fanfanyir** [comment]
<FullCalendar  :datesRender="datesRender" />

**Comment by fanfanyir** [comment]
<FullCalendar :datesRender="datesRender"/>

**Comment by fanfanyir** [comment]
> events prop set a func can listen,but I don't know how to add events to the view.

<FullCalendar :datesRender="datesRender"/>

**Comment by fanfanyir** [comment]
`<FullCalendar :datesRender="datesRender"/>`

**Comment by rjsnh1522** [comment]
> `<FullCalendar :datesRender="datesRender"/>`

Its not working for me.
can u please tell more

**Comment by jabirbarber-elder** [comment]
Any updated on this for v5?
What is the correct way of listening to date changes?
