### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-vue#25]
I compiled a list of missing properties from `OptionsInput` in the core repo ([#4690](https://github.com/fullcalendar/fullcalendar/issues/4690)), and most of these are also missing here:

- `allDayHtml` (entirely undocumented, so this might be by choice)
- `eventDragMinDistance`
- `eventResourceEditable`
- `eventSourceFailure`
- `eventSourceSuccess`
- `forceEventDuration`
- `progressiveEventRendering`
- `selectLongPressDelay`
- `selectMinDistance`
- `timeZoneParam`
- `titleRangeSeparator`
- `refetchResourcesOnNavigate` (scheduler)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Is there something specific to the Vue component?

**Comment by arshaw** [comment]
I added these. will be in the next release. will comment again when that happens

**Comment by arshaw** [comment]
missing props have been added in 4.2.0
https://github.com/fullcalendar/fullcalendar-vue/releases/tag/v4.2.0
