### ISSUE TITLE
Height property is being ignored

### ISSUE THREAD

**Issue by phyroslam** [fullcalendar/fullcalendar-vue#26]
If I try to use the height property this is being ignored:

<FullCalendar
      height="200"
      class="demo-app-calendar"
      ref="fullCalendar"
      defaultView="dayGridMonth"
      :header="{
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      }"
      :plugins="calendarPlugins"
      :weekends="calendarWeekends"
      :events="calendarEvents"
      @dateClick="handleDateClick"
    />

https://codesandbox.io/s/fullcalendar-vue-vhx08

**Comment by mediaessenz** [comment]
height has to be a number, but you enter a string.
Change height="200" to :height="200" will do the job.

**Comment by acerix** [comment]
@mediaessenz  Thanks for the fix
