### ISSUE TITLE
@eventRender ignores return false 

### ISSUE THREAD

**Issue by mediaessenz** [fullcalendar/fullcalendar-vue#27]
I currently try to add a category filter for events to a vue app which uses this fullcalendar component.

The documentation for the used @eventRender event, which can be found here: https://fullcalendar.io/docs/eventRender
says: "The function can also return false to completely cancel the rendering of the event." 

This is currently not working.
To reproduce see: https://codesandbox.io/s/fullcalendar-vue-mxi8t

The descriped second posibility:
"The function can also return a brand new element that will be used for rendering instead. For all-day background events, you must be sure to return a <td>."
seem also not to work.

**Comment by zintj** [comment]
Turns out "The function can also return a brand new element that will be used for rendering instead..."
is exactly what I'll need in my project if I understand it right: Need to be able to completely change how an event looks in the cal. Watching this closely!

**Comment by arshaw** [comment]
`eventRender` is implemented as a Vue emitted event, and its impossible to detect what a return value is from a handler, so what I've done is reimplemented `eventRender` as a property instead. you'll be able to return `false` or a DOM node from the function you pass in as this prop.

`eventRender` as an *emitted event* will still continue to work for the time being. but if you want to take advantage of the new behavior you have to convert it to a prop.

this is implemented in master. will release soon

**Comment by arshaw** [comment]
released in 4.2.0
https://github.com/fullcalendar/fullcalendar-vue/releases/tag/v4.2.0

for `eventRender`, pass a function in as a prop!
