### ISSUE TITLE
refetchResourcesOnNavigate has no effect in vue component?

### ISSUE THREAD

**Issue by j-fdion** [fullcalendar/fullcalendar-vue#29]
I have enabled refetchResourcesOnNavigate in my vue component and the fetchInfo arg in the resource callback function is never called on navigation and is always returning an empty object.

https://codesandbox.io/embed/fullcalendar-vue-32tp2

If you look at the console output, it only output once with an empty fetchInfo object.

I've been asked to create this issue in the fullcalendar vue component repo instead of the main repo, but I can see it's already been discussed in issue #25 

Related:
https://github.com/fullcalendar/fullcalendar/issues/4697

**Comment by arshaw** [comment]
see my latest comment on #25. will be released soon

**Comment by arshaw** [comment]
missing props have been added in 4.2.0
https://github.com/fullcalendar/fullcalendar-vue/releases/tag/v4.2.0
