### ISSUE TITLE
Events drag and drop problem

### ISSUE THREAD

**Issue by bulletbs** [fullcalendar/fullcalendar-vue#3]
Hi! Today I tried to make droppable events by Draggable plugin. (earlier I did the same at my own Vue-component)
What have been done:
1. Import plugins:
`import interactionPlugin, { Draggable } from '@fullcalendar/interaction';`
2. Make Interaction plugin available:
`calendarPlugins: [ interactionPlugin, timeline ],`
3. Create Draggable object:
`new Draggable(document.getElementById('planned-tasks'), {
					itemSelector: '.fc-event',
					eventData: function(eventEl) {
						return  {
							title: eventEl.innerText,
							duration: "02:00"
						};
					}
				});`

But when I drop event on calendar - nothing happens, like when `Draggable.eventData` returns object with `create:false` attribute.
I also have problem with dragging events inside of calendar, when I try to drag event - nothing happens. And no errors in console in both cases.
Only event resize works fine.
Is it problem with InteractionPlugin support or something?

P.S.: just in case I restart my browser before sending an issue =)

**Comment by arshaw** [comment]
Can you make a reduced test case? this debugging template will help as a starting point:
https://codesandbox.io/s/8xyz32l0r8

https://fullcalendar.io/reduced-test-cases

**Comment by laurensiusadi** [comment]
@arshaw using the codesandbox, I try dragging the only event there, but it doesn't move. Is there anything need to be enabled to make event drag works?

**Comment by bulletbs** [comment]
Strange thing. 
In CodeSandBox it's works fine [https://codesandbox.io/s/n9x732zyrj](url)
But when I put this component in my application - problem is still there.

**Comment by Damanii** [comment]
Same issue with me currently. I updated to
`@fullcalendar/core@4.3.1`
`@fullcalendar/daygrid@4.3.0`
`@fullcalendar/vue@4.3.1`
though and it seems to be working now. Dragging, dropping, resizing.

**Comment by good-marketing** [comment]
Hi, I have the issue that the drag only works on the  "timelineDay" view. 

The events on the timeGridWeek or timeGridDay view do not get rendered properly . (or not at all)  after dropping. Also the events are not editable or dragable after dropping. 

I created an test case here: https://codesandbox.io/s/vue-template-er5p0

I am using
`  
"@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",
    "@fullcalendar/timeline": "^4.3.0",
    "@fullcalendar/vue": "^4.3.1"
`

Thanks

**Comment by Bijan-mp** [comment]
I have the same problem, drag-drop does not work on Vue fullcalender.
Please tell me what am I to do?

**Comment by yujin1st** [comment]
In my case was simple answer:
Set `new Draggable (document.getElementById('planned-tasks'))` AFTER you load data, not in `mounted` or `created`
