### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by yooouuri** [fullcalendar/fullcalendar-vue#31]

**Comment by acerix** [comment]
Are you looking for TypeScript version as described here?

https://vuejs.org/v2/guide/typescript.html

**Comment by tmladek** [comment]
Right now, trying to import `@fullcalendar/vue` results in the following error:

```
TS7016: Could not find a declaration file for module '@fullcalendar/vue'. '/[...]/node_modules/@fullcalendar/vue/main.umd.js' implicitly has an 'any' type.
```

I assume they mean this, in any case it's the error that brought me here :)

**Comment by tmladek** [comment]
Any news?

**Comment by yooouuri** [comment]
We are missing types for fullcalendar vue

**Comment by haexhub** [comment]
Would be really nice if you could provide the types declaration file for typescript support!

**Comment by tmladek** [comment]
Any news yet?

**Comment by tmladek** [comment]
"Latest commit af28b03 on Aug 12, 2019" - is anyone still maintaining this project?

**Comment by nadershamma** [comment]
Having an issue with this as well, is there a plan to add one?

**Comment by nadershamma** [comment]
I decided to give this a go, first time writing types definition for a package. I have it working in our project. I'll be honest first time I have written a types defs, was a lot of pocking around until the IDE and compiler stopped complaining but it may not be the right way. 

There is an issue around using the $refs api with class based vues, [see this stackoverflow thread](https://stackoverflow.com/questions/46505813/vuejs-typescript-this-refs-reffield-value-does-not-exist)

So I created an interface type in the defs called FullCalendarComponent to resolve this. 

My question now is where do I place these files? shall I stick them in this repo in src and you bundle it up into the package you have on npm or do we create a new package? Probably need help with the latter.

**Comment by RipkensLar** [comment]
A workaround would be to make a typescript definition file where you simply do something like this:
```
declare module '@fullcalendar/vue';
```
That way your code compiles, but you still don't have "real" typescript support.

**Comment by nadershamma** [comment]
If anyone is looking for type definitions I have submitted some to DefinitelyTyped https://www.npmjs.com/package/@types/fullcalendar__vue

**Comment by arshaw** [comment]
@nadershamma, thank you so much for writing those definitions! They really helped me get oriented while thinking about this issue.

After a bit of investigation, I decided to rewrite the fullcalendar vue connector in TypeScript (a language I love) and have the definitions be auto-generated. Just like what others have suggested in this thread. I already do something like this for the React connector.

This is all available in the [release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features).

Package info: https://www.npmjs.com/package/@fullcalendar/vue/v/5.0.0-rc
Example project: https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/vue-typescript

Please try these out and report any problems in a separate issue. Thank you!
