### ISSUE TITLE
Passing complex template expressions can cause unnecessary re-render

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-vue#34]
I just spent a good amount of time trying to figure out why my calendar would constantly re-render, and thought I'd share my findings:

Due to the way vue works, prop values that are calculated inline, e.g.

`:header="showHeader ? { left: '', center: 'title', right: '' } : false"`

are re-calculated every time the template renders. That means that every time the template updates, a new object (with the same props) is passed to the FullCalendar instance, even if the relevant properties (here `showHeader`) didn't change. Since there is a watcher for all properties, the watcher for `header` will trigger on every template update, and issue a full re-render.

Demo: https://codesandbox.io/s/fullcalendar-vue-uencg

An obvious workaround is to move the calculation to a computed property (see: https://github.com/vuejs/vue/issues/4060#issuecomment-257088477), however it would be nice if the vue component would also guard against this behavior, e.g. by performing a property-equals check on the new & old value when the watcher triggers.

**Comment by arshaw** [comment]
note to self: should use `deepEqual` to decide if we should `recordDirtyOption`: https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/FullCalendar.js#L106-L111

**Comment by arshaw** [comment]
fixed in v4.3.1
