### ISSUE TITLE
Event properties in calendarEvents are not updated

### ISSUE THREAD

**Issue by sibbngheid** [fullcalendar/fullcalendar-vue#35]
Reproduction: https://codesandbox.io/s/fullcalendar-vue-vijjj

In this example i put editable true on my events:
```javascript
calendarEvents: [
        // initial event data
        { 
          title: "Event Now",
          start: new Date(),
          editable: true
        }
      ]
```
And I'm logging eventDrop actions in eventDropped method:
```javascript
    eventDropped(info) {
      console.log("--------------");
      console.log("Dropped event:", info.event.start);
      console.log(
        "Event from api:",
        this.$refs.fullCalendar.getApi().getEvents()[0].start
      );
      console.log("Event from vue:", this.calendarEvents[0].start);
    }
```
When I drop event to another date `this.calendarEvents[0].start` is not changing. Its value same as initialized.

Also when you add new event by clicking a date, this event is backs to its initilialized date.

**Comment by predragnikolic** [comment]
If someone run into this problem, here is how I solved it.

On the full calendar component listen on the `eventDrop`.
``` <FullCalendar ... @eventDrop="eventDrop">```

In eventDrop function:

```function eventDrop(info) {
  // I assume you also have id on event
  let index = this.calendarEvents.findIndex(event => event.id === Number(info.event.id))
  this.calendarEvents[index].start = info.event.start
  this.calendarEvents[index].end = info.event.end
}
```


This will keep `calendarEvents` in sync, and it fixes this problem:
> Also when you add new event by clicking a date, this event is backs to its initilialized date.

**Comment by arshaw** [comment]
I have written a new Vue example with v5 that more clearly communicates best practices with the new `initialEvents` setting: https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/vue/src/DemoApp.vue

Changing your approach to follow these best practices will avoid this problem.

In short: use `initialEvents` to specify the events in the beginning, and then use FullCalendar's API from then on.

If you need a more robust solution, take a look at the [vuex example](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue-vuex)
