### ISSUE TITLE
locales doesn't change firstDay

### ISSUE THREAD

**Issue by sibbngheid** [fullcalendar/fullcalendar-vue#36]
Reproduction: https://codesandbox.io/s/fullcalendar-vue-vijjj

I set `locale="tr"` in this example. First day should be `Pzt` but it is still `Paz`. Workaround this issue by adding `:firstDay="1"`

**Comment by acerix** [comment]
Thanks for the report and workaround, confirmed.

**Comment by arshaw** [comment]
When you specify a string locale name but don't include the locale data, the day/month names will be translated, but nothing else about the calendar, like first day-of-week, will be correct. you need to include the external locale data for that.

**Comment by arshaw** [comment]
please see: https://fullcalendar.io/docs/locale

**Comment by erhanfirat** [comment]
@arshaw what do you mean by "you need to include the external locale data for that" 
it would be perfect if you give an example?
