### ISSUE TITLE
Bug: Some options don't seem to work unless v-bind

### ISSUE THREAD

**Issue by andrewalex** [fullcalendar/fullcalendar-vue#39]
### Bug Reports
https://codesandbox.io/s/fullcalendar-vue-ym6zw

allDaySlot line 18..   ":allDaySlot" works ok
I cant seem to get nowIndicator to work at all

**Comment by acerix** [comment]
I don't see "nowIndicator" in your demo but it seems to work fine:

https://codesandbox.io/s/fullcalendar-vue-peh62

**Comment by andrewalex** [comment]
I apologize. It appears I don't know how to use codesandbox.io

hopefully this one works  https://codesandbox.io/s/fullcalendar-vue-covs2

```
allDaySlot="false"
nowIndicator="false"
```

behaves differently from
```
:allDaySlot="false"
:nowIndicator="false"

```

**Comment by acerix** [comment]
I beleive that is required for Vue to parse "false" as a boolean instead of the string "false" which evaluates to `true`.

https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean

**Comment by andrewalex** [comment]
looks like it'll be fundamental
