### ISSUE TITLE
Uncaught TypeError: Cannot read property 'viewsWithButtons' of undefined

### ISSUE THREAD

**Issue by jkque** [fullcalendar/fullcalendar-vue#4]
https://codesandbox.io/s/54jpnjnz3n

Set props :header="false" and :navLinks="true" as seen in the codesandbox
When clicking the navlink nothing happen in codesandbox. 
In my project this is the error
![Annotation 2019-04-08 205931](https://user-images.githubusercontent.com/5366722/55725985-64154380-5a41-11e9-8ecc-d7ff26903e36.jpg)

**Comment by arshaw** [comment]
thanks. i realized this is a problem in core:
https://github.com/fullcalendar/fullcalendar/issues/4619
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by jkque** [comment]
Done, i hope it will be fixed soon.
Thanks @arshaw

**Comment by jkque** [comment]
Awesome
