### ISSUE TITLE
Bug: old licence key is not working for fullcalendar-vue

### ISSUE THREAD

**Issue by suyogshiftcare** [fullcalendar/fullcalendar-vue#40]
I have purchased a licence for fullcalendar in 2016. I have recently ported my application to vue application. I reused the licence in the vue full calendar but I have been getting please use a valid licence key. The licence works if I use it in the same key in old way but not with this fullcalendar-vue component. Please advice what I should do? do I need a separate key for it?
![Screen Shot 2019-07-23 at 2 44 20 pm](https://user-images.githubusercontent.com/44953464/61718834-1a115d00-ada7-11e9-983c-9df4b48227a1.png)
![Screen Shot 2019-07-23 at 2 50 34 pm (1)](https://user-images.githubusercontent.com/44953464/61719050-88eeb600-ada7-11e9-8494-038d8d9a2bf5.png)

**Comment by acerix** [comment]
I just responded to your email; the license needs to be renewed since it only includes 1 year of updates.
