### ISSUE TITLE
locales doesn't change the title of the buttons

### ISSUE THREAD

**Issue by qinzitong** [fullcalendar/fullcalendar-vue#45]
### Bug Reports
```
<FullCalendar
      class='demo-app-calendar'
      ref="fullCalendar"
      defaultView="dayGridMonth"
      :header="{
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      }"
      :plugins="calendarPlugins"
      :weekends="calendarWeekends"
      :events="calendarEvents"
      @dateClick="handleDateClick"
      locale="zh-cn"
    />
```

### Feature Requests
the group of buttons title should be the chinese, when I set the locale is zh-cn
<img width="1084" alt="屏幕快照 2019-08-14 10 48 19" src="https://user-images.githubusercontent.com/5271315/62991152-0fffed00-be81-11e9-8668-80d4d10ce261.png">

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
You need to load the locale as described here:

https://fullcalendar.io/docs/locale#loading-locales-for-an-es6-build-system

https://codesandbox.io/s/fullcalendar-vue-udkqf
