### ISSUE TITLE
In the docs: <style lang='scss'> must be 'css'.

### ISSUE THREAD

**Issue by Jalliuz** [fullcalendar/fullcalendar-vue#46]
I was just installing this with yarn + webpack/encore and when I just copied the documentation examples and performed a "yarn encore dev --watch" to build everything I got the error "Module parse failed: Unexpected character '@'".
The files are in css, not scss.
So:
```
<style lang='scss'>
    @import '~@fullcalendar/core/main.css';
    @import '~@fullcalendar/timeline/main.css';
    @import '~@fullcalendar/resource-timeline/main.css';
</style>
```
Needs to be:
```
<style lang='css'>
    @import '~@fullcalendar/core/main.css';
    @import '~@fullcalendar/timeline/main.css';
    @import '~@fullcalendar/resource-timeline/main.css';
</style>
```

**Comment by acerix** [comment]
Thanks for the report, I can see the error in the docs:

https://fullcalendar.io/docs/vue#css

Since CSS does not need pre-processing, I beleive it should be included like in the demo project, eg:

```vue
<script>
import "@fullcalendar/core/main.css";
import "@fullcalendar/daygrid/main.css";
</script>
```

**Comment by Jalliuz** [comment]
It was ofcourse also resolved by adding "node-sass" and "sass-loader" to my webpack encore setup (with yarn add node-sass sass-loader) and enabling it in the Encore settings with ".enableSassLoader()"

**Comment by arshaw** [comment]
this is no longer applicable because in v5, which has [just been release](https://fullcalendar.io/blog/2020/06/v5-official), all plugins load their own css and you don't need to write your own css import statements.
