### ISSUE TITLE
Consolidate configuration parameters to avoid duplication

### ISSUE THREAD

**Issue by divdax** [fullcalendar/fullcalendar-vue#47]
Currently you have to define each config parameters like so:
```
<FullCalendar
      ref="fullCalendar"
      :selectable="selectable"
      :plugins="plugins"
      :defaultView="defaultView"
      :firstDay="firstDay"
      :nowIndicator="nowIndicator"
      :allDayText="allDayText"
      :slotDuration="slotDuration"
      :slotLabelFormat="slotLabelFormat"
      :slotLabelInterval="slotLabelInterval"
      :locale="locale"
      :height="height"
      :editable="editable"
      :datesAboveResources="datesAboveResources"
      :buttonText="buttonText"
      :header="header"
      :views="views"
      :resources="resources"
      :events="events"
      :resourceRender="resourceRender"
      :columnHeaderHtml="columnHeaderHtml"
      :eventRender="eventRender"
/>
```
Everything is duplicated and feels wrong:
```
export default {
  components: {
    Layout,
    FullCalendar,
    TextInput
  },
  data() {
    return {
      plugins: [
        dayGridPlugin,
        timeGridPlugin,
        listPlugin,
        interactionPlugin,
        momentPlugin
      ],
      defaultView: "timeGridWeek",
      firstDay: 1,
      nowIndicator: true,
      allDayText: "Ganztägig",
      slotDuration: "00:15",
      slotLabelFormat: "HH:mm",
      slotLabelInterval: "00:30",
      locale: "de",
      height: "auto",
      editable: true,
      datesAboveResources: true,

      ...

    };
  },
}
```
Using a simple config parameter like so would be much cleaner:
```
<FullCalendar
      ref="fullCalendar"
      :config="calendarConfig"
/>
```
```
export default {
  data() {
    return {
      calendarConfig: {
         plugins: [
            dayGridPlugin,
            timeGridPlugin,
            listPlugin,
            interactionPlugin,
            momentPlugin
        ],
        defaultView: "timeGridWeek",
        ...
      }
    };
  },
}
```

**Comment by dneuschaefer-rube** [comment]
Vue allows you to bind objects in order to pass multiple properties at once, so you can already do this like:

```vue
<FullCalendar
      ref="fullCalendar"
      v-bind="calendarConfig"
...
/>
```

**Comment by jackleblack** [comment]
I made an easy example from the playground and this not work.
Anybody have an idea ?

https://codesandbox.io/s/fullcalendar-vue-1c39z

**Comment by arshaw** [comment]
i implemented this in v5. now there is a single root `options` props. please let me know what you think

- changelog: https://fullcalendar.io/docs/v5/upgrading-from-v4#vue-connector
- example: https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/vue/src/DemoApp.vue

**Comment by arshaw** [comment]
latest v5 blog post: https://fullcalendar.io/blog/2020/04/new-ui-features-beta

**Comment by arshaw** [comment]
this has been released in v5! https://fullcalendar.io/docs/vue

**Comment by divdax** [comment]
Great job @arshaw! Really appreciate you made this possible! ❤️

**Comment by d-damien** [comment]
Reducing duplication is good, but I found it complicated to have reactivity on a single prop now. It's a core feature of JS frameworks ; I think it's too bad it has been removed : couldn't we have both single object and single prop reactivity (latter overriding the former) ?

Use case : I have many kinds of calendars in a software, but with one usual set of options used globally. So I made a `<basic-calendar>` component, and others "inherit" its options by calling `<basic-calendar>` in their template. Passing props would be really practical here. Am I doing this wrong ?

**Comment by d-damien** [comment]
Same for events. I'd like to be able to react to all events in parent components without having to emit them manually, like with `v-on="$listeners"`. I have this in my options object :
```
datesSet: e => this.$emit('datesSet', e),
dateClick: e => this.$emit('dateClick', e),
eventClick: e => this.$emit('eventClick', e),
... etc for all events
```
