### ISSUE TITLE
Events dissappear from resourceTimeline view when resourceTimeGridPlugin is added to plugins

### ISSUE THREAD

**Issue by proquibas** [fullcalendar/fullcalendar-vue#48]
### Bug Reports
When I try to integrate both plugins, resource-timeline and resource-timegrid in the same calendar the events disappear from the calendar.

### Reproduction
https://codesandbox.io/s/fullcalendar-vue-h1klz
Just comment and uncomment the line 48 of the resourceTimeGridPlugin plugin to see the results.

Thank you.

**Comment by proquibas** [comment]
Thank you @acerix , hope you will fix it soon. :)

**Comment by GertjanRoke** [comment]
I have the same problem but I see them but at the bottom, maybe this can help?

If you want more code please let me know! I would love to help.

![image](https://user-images.githubusercontent.com/6010509/65326207-3c5e0600-dbb1-11e9-810f-f0cabb46407b.png)

**Comment by arshaw** [comment]
@proquibas for some reason you were using @fullcalendar/vue version 4.0.2-beta whereas all the other deps were non-beta. I updated all your deps to the latest releases and it works now:

https://codesandbox.io/s/fullcalendar-vue-ihfdx

**Comment by proquibas** [comment]
@arshaw , I check my package.json, and that's what I have configured about fullcalendar packages:

>   "@fullcalendar/core": "4.3.1",
>     "@fullcalendar/daygrid": "4.3.0",
>     "@fullcalendar/interaction": "4.3.0",
>     "@fullcalendar/list": "4.3.0",
>     "@fullcalendar/moment": "4.3.0",
>     "@fullcalendar/resource-common": "4.3.1",
>     "@fullcalendar/resource-timegrid": "4.3.0",
>     "@fullcalendar/resource-timeline": "^4.3.0",
>     "@fullcalendar/timegrid": "4.3.0",
>     "@fullcalendar/vue": "4.3.1",

I think I have the same versions like in your sandbox but it still not working. If I activate the plugin in the calendarPlugins object both views are not showing the events even if I don't use one of them. I mean, activating the plugin I can see the events in the timeGridWeek view, but not in the other two views.

Thank you.
