### ISSUE TITLE
Use kebab-case for event names

### ISSUE THREAD

**Issue by hebinet** [fullcalendar/fullcalendar-vue#49]
Hello,

It took me over an hour to find this out, but i think that the Event-System for this Vue component is broken. It is impossible to listen to an event via '@' or 'v-on:'.

The Events emited by the fullcalendar component are CamelCase, but should be in kebab-case.

Here is a briefe excerpt from the official VueJS documentation:
> Unlike components and props, event names will never be used as variable or property names in JavaScript, so there’s no reason to use camelCase or PascalCase. Additionally, v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity), so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.
> 
> For these reasons, we recommend you always use kebab-case for event names.

Here is a code snippet how I can reproduce it (I removed everything which is not related to the problem)
```html
<fullcalendar
...
        default-view="dayGridWeek"
        editable="true"
        startEditable="true"
        durationEditable="false"
        @eventDrop="handleEventDrop"
...
    ></fullcalendar>
```

And in the vue instance like this:
```js
const pickups = new Vue({
    el: '#calendar',
    data() {
        return {
            plugins: [dayGridPlugin, interactionPlugin],
            events: 'events get loaded by url'
        }
    },
    methods: {
        handleEventDrop(eventInfo) {
            console.log(eventInfo)
        }
    }
});
```
As soon as I drop an exisiting event on another date/time, the (Chrome) Browser prints the following in the console
> [Vue tip]: Event "eventdrop" is emitted in component <FullCalendar> but the handler is registered for "eventDrop". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "event-drop" instead of "eventDrop".

Is it possible to change the emited events to kebab-case or provide another method to listen to the event like it is done with 'eventRender' or so...

Kind regards

### Is your bug/feature applicable to the core project, without Vue?
No, its only a problem in combination with VueJS

**Comment by acerix** [comment]
Thanks for the detailed report.  It sounds like they should be kebab-case from that documentation but I didn't have any issue or get any warning when I tried it in the debug template:

https://codesandbox.io/s/fullcalendar-vue-zofdp

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) that shows the issue/warning?

**Comment by hebinet** [comment]
Hello, I managed to create a laravel project with laravel mix to compile the js assets and I could reproduce the warning on Chrome and Firefox ( in Arch-Linux ).

You can clone the repository from here:
https://github.com/hebinet/fullcalendar-vue-event-listener-bug

After that, just do the following to get the application working:

- composer install
- npm install
- npm run dev
- php artisan serve

Assuming that you have php, composer, nodejs and npm installed on your client, you should see the following output:

> Laravel development server started: <http://127.0.0.1:8000>

If you open the given url you should see the calendar in week view.
Just drop the displayed event from one day to another and you should see the console log message with the warning.

**Comment by stripedbug** [comment]
Hi hebinet 
I had the same issue. Haven't cloned your repo but considering the problem i think you made the same mistake and embedded fullcalendar component directly to the blade file. Instead create a seperate component for your calendar view and implement your calendar logic into the component.  This will solve all further camelcase issues.

**Comment by hebinet** [comment]
Hi stripedbug,
I havent't tried it yet, but this looks like a workaround for me rathere than a solution.

Components are designed to be used as a standalone thing in an application.
I don't think that it is intended, to wrap this component into another component, just to make this work.

**Comment by stripedbug** [comment]
> Hi stripedbug,
> I havent't tried it yet, but this looks like a workaround for me rathere than a solution.

It seems like a workaround but actually it is for escaping the limitations of HTML. As vue dev console pointed ,"v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity)"

**Comment by cyberbobcity** [comment]
I'm having the same issue talked about here, but I don't fully understand what the solution is to get around it? I tried putting the calendar in its own component, but I still get the same error. Can you explain more about how to put the "calendar view" in its own component? It would be very much appreciated.

**Comment by ryanjkelly** [comment]
@cyberbobcity, something like this...

```
Vue.component("fullcalendar-wrapper", {
  template: '<fullcalendar v-on:dateClick="onDateClick"></fullcalendar>',
  methods: {
    onDateClick: function(i){ this.$emit("date-click", i); }
  }
});
```
Then, 
```
<fullcalendar-wrapper v-on:date-click="methodForDealingWithDateClick"></fullcalendar-wrapper>
```
Remember, you'll need to do this for any option you plan to use. [Here's a list](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js) of all the options.

**Comment by cyberbobcity** [comment]
In this scenario, how exactly do you setup the calendar-logins for the day grid and interaction?

**Comment by axeh** [comment]
I am facing the same problem.
What is the proper solution for this issue?

**Comment by best8248** [comment]
#main.umd.js

line 348

_this.$emit.apply(_this, [emissionName].concat(args));
=> _this.$emit.apply(_this, [emissionName.toLowerCase()].concat(args));

**Comment by jacekkarczmarczyk** [comment]
@axeh 
Don't use html templates, use `template` tag (`Vue.extend({ template: '<div></div>'})` or `script type="text/x-template"` or SFC
This https://codepen.io/jkarczm/pen/NWqRjwp works
This https://codepen.io/jkarczm/pen/poJEPdd won't work

@best8248 
I don't think so, event name must be kebab-cased when emitted, not only lowercased

**Comment by iiibbbmmm** [comment]
According to [Props — Vue.js](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case), Vue component props as well as events should be kebab-case to make them work in in-DOM template.

My workaround: 
```html
<full-calendar ... @date-click="handleDateClick" />
```

```js
...
 mounted() {
    const camelize = str => str.split('-').map((item, index) => index ? item.charAt(0).toUpperCase() + item.slice(1).toLowerCase() : item).join("")
    Object.keys(this.$refs.fullCalendar._events).forEach(name=>this.$refs.fullCalendar._events[camelize(name)] = this.$refs.fullCalendar._events[name])
}
...
```

**Comment by arshaw** [comment]
Sorry about taking a long time to address this.

As of v5, this is a moot point. the v5 vue API requires you to pass-in a root-level config object. The keys can be cased however you want.

docs: https://fullcalendar.io/docs/vue
