### ISSUE TITLE
How to use with NUXT?

### ISSUE THREAD

**Issue by RMFogarty** [fullcalendar/fullcalendar-vue#5]
Trying to figure out how to use this with NUXT. The default vue setup will not work because it does not support server side rendering. I would expect to be able to call this via a plugin and have tried a few different ways such as below:

Created a new plugin FullCalendarVue.js:

```
import Vue from 'vue';
import FullCalendar from '@fullcalendar/vue'
import dayGridPlugin from '@fullcalendar/daygrid'

// Vue.use(FullCalendar);
Vue.component('FullCalendar', FullCalendar);
// Vue.component('dayGridPlugin', dayGridPlugin);
Vue.use(dayGridPlugin);
```

Added the plugin to nuxt.config.js:

```
  plugins: [
    {mode: 'client', src: '~/plugins/FullCalendarVue'},
  ],
```

On the vue page I wrap the calendar component in no-ssr tags:

```
<no-ssr>
        <FullCalendar
            defaultView="dayGridMonth"
            :plugins="calendarPlugins"
        />
</no-ssr>
```

This seems to load the fullcalendar plugin but I keep getting errors that "dayGridPlugin is not defined". Any suggestions on how to setup?

**Comment by nucle** [comment]
I tried different solutions but nothing works with NUXT. Any suggestions or examples?

**Comment by stellasoft-george** [comment]
@RMFogarty @nucle 

Hope this helps you, this is how I got it working with nuxt:

1. Create a base component, mine is at `components/Calendar.vue` and contains the following (copied from the full calendar documentation)

```
<template>
    <FullCalendar defaultView="dayGridMonth" :plugins="calendarPlugins" />
</template>

<script>
    import FullCalendar from '@fullcalendar/vue'
    import dayGridPlugin from '@fullcalendar/daygrid'

    export default {
        components: {
            FullCalendar // make the <FullCalendar> tag available
        },
        data() {
            return {
                calendarPlugins: [ dayGridPlugin ]
            }
        }
    }
</script>
```

2. In a plugin at `plugins/full-calendar.js` I have the following
```
import Vue from 'vue';
import Calendar from '~/components/calendar'

Vue.component('full-calendar', Calendar);
```

3. And then my `nuxt.config.js` has the following
```
plugins: [{src: '~/plugins/full-calendar', ssr: false}],
```

The above works for me in universal mode. Defining a base component is what full calendar recommend in the docs so I've done that, and `ssr: false` seems to be the key to avoid Element is not defined errors

**Comment by RMFogarty** [comment]
That works! I didn't even realize you could create plugins from components. Thanks for posting this.

**Comment by iamqinglong** [comment]
Hello Guys, I'm experiencing "Element is not defined" errors.  I tried ur steps @stellasoft-george .  What do u think i'm missing ? I was trying to import the Calendar.vue component in another .vue file.

**Comment by lando-cal** [comment]
you don't need to import the Calendar.vue, as the plugin does that for ya.
Just use <full-calendar /> in the page, and it should show up.
Although, I haven't gotten the CSS to load properly from the node_modules path yet.

**Comment by chrno1209** [comment]
> Hello Guys, I'm experiencing "Element is not defined" errors. I tried ur steps @stellasoft-george . What do u think i'm missing ? I was trying to import the Calendar.vue component in another .vue file.

I am having the same issue, not sure how to fix it, even following @stellasoft-george solution

**Comment by EstebanFuentealba** [comment]
> > Hello Guys, I'm experiencing "Element is not defined" errors. I tried ur steps @stellasoft-george . What do u think i'm missing ? I was trying to import the Calendar.vue component in another .vue file.
> 
> I am having the same issue, not sure how to fix it, even following @stellasoft-george solution
> 
> EDIT: solved the issue myself, got wrong direction when implementing following @stellasoft-george, it works now, thanks :)

@chrno1209 you can implement 

```
<template>
      <no-ssr>
      <Calendar />
      </no-ssr>
</template>
<script>
let components = {};
if(process.browser) {
    const Calendar = require('~/components/Calendar').default;
    components = {
        Calendar
    }
}
export default {
 components 
}
</script>
<style lang='scss'>
@import '~@fullcalendar/core/main.css';
@import '~@fullcalendar/daygrid/main.css';
</style>
```

**Comment by langtuflame** [comment]
> > > Hello Guys, I'm experiencing "Element is not defined" errors. I tried ur steps @stellasoft-george . What do u think i'm missing ? I was trying to import the Calendar.vue component in another .vue file.
> > 
> > 
> > I am having the same issue, not sure how to fix it, even following @stellasoft-george solution
> > EDIT: solved the issue myself, got wrong direction when implementing following @stellasoft-george, it works now, thanks :)
> 
> @chrno1209 you can implement
> 
> ```
> <template>
>       <Calendar />
> </template>
> <script>
> let components = {};
> if(process.browser) {
>     const Calendar = require('~/components/Calendar').default;
>     components = {
>         Calendar
>     }
> }
> export default {
>  components 
> }
> </script>
> <style lang='scss'>
> @import '~@fullcalendar/core/main.css';
> @import '~@fullcalendar/daygrid/main.css';
> </style>
> ```

i following you. i use  if(process.browser) {}. that's work but i when i use nuxt-link in project. nuxt-link not working. How to fix it? Help me pls :(

**Comment by benben994** [comment]
I've followed @stellasoft-george solution which works great in local.
But when I npm run build && start for production mode,
`import Calendar from '~/components/calendar'`
The path is not recognized because there's no components in production,
did anyone face this issue?

**Comment by pires12** [comment]
Hello @stellasoft-george  i just follow your code, and i got error in console say "viewType "" is not available. Please make sure you've loaded all neccessary plugins", any idea?

**Comment by ijunaid8989** [comment]
@pires12 how are you trying to destory calendar?

**Comment by pires12** [comment]
@ijunaid8989 no, i want to display calendar

**Comment by amirakbulut** [comment]
> Hello @stellasoft-george i just follow your code, and i got error in console say "viewType "" is not available. Please make sure you've loaded all neccessary plugins", any idea?
> 
> ![111](https://user-images.githubusercontent.com/26146337/88540206-7d366f00-d04d-11ea-9cd7-3cf4c84440c5.PNG)

Same issue here, after implementing @stellasoft-george his answer.

**Comment by PichurChill** [comment]
> > Hello @stellasoft-george i just follow your code, and i got error in console say "viewType "" is not available. Please make sure you've loaded all neccessary plugins", any idea?
> > ![111](https://user-images.githubusercontent.com/26146337/88540206-7d366f00-d04d-11ea-9cd7-3cf4c84440c5.PNG)
> 
> Same issue here, after implementing @stellasoft-george his answer.

use `:options`instead
```
 <FullCalendar :options="calendarOptions" />
```

see [doc](https://fullcalendar.io/docs/vue)

**Comment by amine-elghazali** [comment]
guys ! any updates how to implement FullCalendar in Nuxt3 pleaae !! I've searching for a while and nothing works for me !  please help

**Comment by MilenaPetkanova** [comment]
> guys ! any updates how to implement FullCalendar in Nuxt3 pleaae !! I've searching for a while and nothing works for me ! please help

I tried to implement it according to the reply [here](https://stackoverflow.com/questions/71754121/how-to-use-fullcalendar-with-nuxt3-getting-vite-ssr-import-1-is-not-defined) but it's not working

**Comment by MilenaPetkanova** [comment]
> guys ! any updates how to implement FullCalendar in Nuxt3 pleaae !! I've searching for a while and nothing works for me ! please help

I just found a solution and posted it in [StackOverflow](https://stackoverflow.com/a/74614260/4607858). Hope it works for you!
