### ISSUE TITLE
Chrome iOS: If date was changed externally, mobile touch no longer works

### ISSUE THREAD

**Issue by longprao** [fullcalendar/fullcalendar-vue#55]
We are using the premium timeline feature. Everything works well until the date was changed by an external event which makes the calendar to redraw, then it is impossible to select date on mobile.

Tested on iPhone XR, iOS 13.1.3, chrome iOS v77.0.3865.103, both resourceTimeline and Timeline-only plugin, using both `:defaultDate="date"` OR

```
watch: {
    date(to) {
      this.$refs.calendar.getApi().gotoDate(to);
    },
  },
```

Link demo: https://demo.knowork.xyz/spaces

Steps to reproduce:

- At first load, time select works.
- Change the date with the top datepicker.
- Time select no longer works (long press does nothing).
- Bonus: If I use the next/back/today button of the calendar (which is hidden in this case), it will work again.

Tried multiple methods of redrawring the calendar like transition, `v-if` with timeout on date change. Nothing works.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
