### ISSUE TITLE
Add custom headers to XHR

### ISSUE THREAD

**Issue by Sauerbier** [fullcalendar/fullcalendar-vue#60]
In this vue version of the fullcalender it seem not to be possible too add custom headers to the xhr fullcalender sends to load events.
In the main projects headers could be added with
`headers: {
            Authorization: 'Bearer ' + getToken()
}`
in the fullcalendar eventSources intialization, but this does not seem to work in vue
My eventsSource obj:
`eventSources: [
        {
          url: '/api/calendar/eventStream',
          color: 'lightblue',
          headers: {
            Authorization: 'Bearer ' + getToken()
          }
        }
      ]`

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4627
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
