### ISSUE TITLE
pre-built release of the Vue component

### ISSUE THREAD

**Issue by denys-vladymyrov** [fullcalendar/fullcalendar-vue#61]
Hello.

It would be great if there was a pre-built Vue component and i can use it without NPM. Some companies do not want to be dependent on external repositories and with pre-built Vue component it would be possible.

Thank you in advance.

**Comment by arshaw** [comment]
The Fullcalendar-Vue connector now publishes a browser-global JS file in `dist/main.global.js`: https://cdn.jsdelivr.net/npm/@fullcalendar/vue@5.2.0/dist/main.global.min.js

A demo of how to use it: https://github.com/fullcalendar/fullcalendar/blob/master/examples/_global-vue.html
