### ISSUE TITLE
Fullcalendar has only dayGridMonth view

### ISSUE THREAD

**Issue by christiancannata** [fullcalendar/fullcalendar-vue#64]
When I try to create a new Fullcalendar vue component and configure it to have another default view different by 'dayGridMonth' it appear an error like this:

> "The FullCalendar view "month" does not exist. Make sure your plugins are loaded correctly."

The same problem is when I try to create a custom view passed in :views params.

`  <FullCalendar :buttonText="{today:$vuetify.lang.t('$vuetify.today')}" :locale="'it'"
                      :titleFormat="{ year: 'numeric', month: 'short' }" :height="window.height"
                      :views="{
timeGridFourDay: {
      type: 'timeGrid',
      duration: { days: 4 },
      buttonText: '4 day'
    }
       }"             
                      :header="{
       left: 'prev,next today',
        center: 'title',
        right: 'timeGridFourDay'
  }"
                      :eventLimit="3" :eventLimitText="$vuetify.lang.t('$vuetify.more')" defaultView="timeGridFourDay"
                      :plugins="calendarPlugins"
                      :events="events"/>`

I get this error: 

> The FullCalendar view "timeGridFourDay" does not exist. Make sure your plugins are loaded correctly.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
