### ISSUE TITLE
Date not displayed properly

### ISSUE THREAD

**Issue by allaniftrue** [fullcalendar/fullcalendar-vue#66]
The date is not displayed when the start and the end date has time.
e.g.
```
{
  "id": 845,
  "title": "Maternity Leave",
  "content": {
    "color_id": 5,
    "description": "Lorem ipsum dolor",
    "google_id": null,
    "event_id": 845,
    "user_id": 2,
    "agent": "admin"
  },
  "start": "2020-01-05 12:00:00",
  "end": "2020-01-09 8:00:00",
  "allDay": false
}
```

Month view is displaying **2020-01-05** to **2020-01-08**

![image](https://user-images.githubusercontent.com/715361/72418539-fb1fe080-37b5-11ea-9bee-b5790de4d67a.png)

Is your bug/feature applicable to the core project, without Vue? Most likely

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can set the time format with https://fullcalendar.io/docs/eventTimeFormat
