### ISSUE TITLE
Some callbacks need to be passed as a property while others are emitted events

### ISSUE THREAD

**Issue by v1nk0** [fullcalendar/fullcalendar-vue#71]
the navLinkDayClick and navLinkWeekClick events don't fire.
Instead the default behaviour of the plugin occurs.

Reproduced here: https://codesandbox.io/s/fullcalendar-vue-fmy5n

Click on a day in week or month view should show an alert, instead it's just navigating to the clicked day.

**Comment by acerix** [comment]
Thanks, confirmed. And only happens in Vue version:

https://codepen.io/acerix/pen/abOWLzN?editors=0011

**Comment by georgehrke** [comment]
@v1nk0 It has to be registered as a property:
https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js#L72

**Comment by v1nk0** [comment]
@georgehrke you're right, passing at as a prop works!
I was expecting the plugin to emit an event, just like _dateClick_ does.

**Comment by acerix** [comment]
Thanks for the update.  I'm not sure why `navLinkDayClick` is a property and `dateClick` an emitted event, seems they should be the same for consistency or the difference should be mentioned in the docs.

**Comment by georgehrke** [comment]
Well, [`navLinkDayClick`](https://fullcalendar.io/docs/navLinkDayClick) can be a string and a function. If you implement it as an emitted event, there is no way to provide a string.

It's obviously up to you how to address this issue, but I think most confusion stems from the fact that developers are not sure whether some option is a property or an emitted event and they end up with trail and error.
Maybe it's possible to generate some documentation from [fullcalendar-options.js](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js)?

**Comment by v1nk0** [comment]
If I'm not mistaking it is an event when it's a **callback** in the official fullcalendar.io documentation (like _dayRender_, _dateClick_, _select_, _unselect_)

**Comment by georgehrke** [comment]
You have similar issues there:
- [dayRender](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js#L150) is a prop
- [dateClick](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js#L168) is an event
- [select](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js#L172) is an event
- [unselect](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js#L173) is an event

**Comment by arshaw** [comment]
btw, v5 (now in beta) does away with the distinction between props and events. everything just lives within a root "options" object.

http://fullcalendar.test/docs/v5/upgrading-from-v4#vue-connector

are you guys okay with this?

**Comment by arshaw** [comment]
v5 was released a little while ago
