### ISSUE TITLE
viewSkeletonRender events don't fire

### ISSUE THREAD

**Issue by Dev1lDragon** [fullcalendar/fullcalendar-vue#72]
the viewSkeletonRender  events don't fire when skeleton rerendered after titleFormat dinamicaly change.

[example](https://codesandbox.io/s/practical-bird-lq1zi)

in my case its destroy perfect-scrollbar initialization

**Comment by Dev1lDragon** [comment]
editable, slotDuration, snapDuration have same problem.

**Comment by acerix** [comment]
The "skeleton" doesn't need to be rendered after changing those settings, `viewSkeletonRender` is only called if something changes the "non-date-related DOM structure" like changing views.

**Comment by Dev1lDragon** [comment]
How i can rebind my custom scrollbar config after that config changes because after changing that config all fc-view-container rerendered an all binded event and configs is lost

**Comment by Dev1lDragon** [comment]
@acerix the problem is that when titleFormat, editable, slotDuration and snapDuration is changed, skeleton is rerendered but no event that show that skeleton is rerendered. i mean i can aced stored node .fc-view-container but when store node inside of that node its not acesible anymore.

**Comment by acerix** [comment]
The "skeleton" is not rerendered in those cases, only the "date structure" which calls `datesRender`.

**Comment by Dev1lDragon** [comment]
@acerix tnx for answers
