### ISSUE TITLE
selectAllow does not fire my event

### ISSUE THREAD

**Issue by Olafxso** [fullcalendar/fullcalendar-vue#73]
I want to use the 'https://fullcalendar.io/docs/selectAllow' method in Vue. 

Here is a codepen of a plain javascript fullcalendar  using selectAllow:
https://codepen.io/olafxso/pen/zYGJyOp 
You can see when you try to select a day on today or before it don't get selected. From tomorrow it is accepted.

I have tried to do something similar from vue.  So I have added '@selectAllow="handleSelectAllow"' just like a date click '@dateClick="handleDateClick"'.
The dateclick works. But the selectAllow not. 

I have made a sample: https://codesandbox.io/s/fullcalendar-vue-m1o2j 
browse to src/DemoApp.vue

**Comment by acerix** [comment]
`selectAllow` is a "prop" so it needs to be set like `:selectAllow="handleSelectAllow"`.

https://codesandbox.io/s/fullcalendar-vue-bgbth
