### ISSUE TITLE
allDaySlot property not working in Vue

### ISSUE THREAD

**Issue by Olafxso** [fullcalendar/fullcalendar-vue#74]
Setting the property allDaySlot to false is not working in Vue component. 
I have created a demo app to show the problem:
https://codesandbox.io/s/fullcalendar-vue-r80xe 

I expect ` allDaySlot="false"`will hide the allday row from the timeGrid

**Comment by acerix** [comment]
It needs to be set like `:allDaySlot="false"`.  Without `:`, it passes `false` as a string which becomes "true".

https://codesandbox.io/s/fullcalendar-vue-c6hj2
