### ISSUE TITLE
Week day classes (e.g. fc-sat) missing when using slotLabelInterval on resource timeline

### ISSUE THREAD

**Issue by darrenparkinson** [fullcalendar/fullcalendar-vue#76]
When adding a slotLabelInterval, the classes for week day are no longer present.  As a result I can no longer style the weekends differently.

[Example Code For The Issue](https://github.com/darrenparkinson/fullcalendar-issue)

**Comment by acerix** [comment]
The classes don't show if the `slotLabelInterval` is specified in hours, it has to be in days:

https://codepen.io/acerix/pen/QWbPxeE?editors=0110

**Comment by darrenparkinson** [comment]
Sorry, that doesn't work for me as I need to be able to see the slots properly in the view?  I don't want the event to take up the whole day as that is not correct?
