### ISSUE TITLE
Support storing events in the Vuex data store

### ISSUE THREAD

**Issue by Cieronpowell** [fullcalendar/fullcalendar-vue#79]
### Bug Reports

https://codesandbox.io/s/fullcalendar-v4-vue-yvhyh

In the above example example I am using Vuex data store. You can see if an external event is dragged in (test1 /test2 at the bottom of the calendar) it is displayed twice. I believe this is because the event is added to fullCalendar locally but then also added to the Vuex data store, which fullCalendar then re-reads in (thats my theory anyway). If I were to navigate to another occurrence of the Calendar using the same data  store, then only one occurrence is visible (again suggesting this second copy only exists in FullCalendars mind) 

Let me know if you need any more examples / info. I did see a couple of other similar(ish) issues on the main tracker, but dont think they are quiet the same issue (although might be same root cause) 

Thanks in advance
Cieron 

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Dropping the event on the calendar will put the event "in the memory" of the calendar, and it seems the way you are using the data store as the source of events will display new events when they are added to the data store. I believe the cleanest way to use the data store like that would be to remove the event that is in memory:

https://codesandbox.io/s/fullcalendar-v4-vue-gpo6n

**Comment by Cieronpowell** [comment]
Thanks that workaround seems to work, it does feel a little hacky though. Do you think there is a better way to set this up with vuex store or is it just the way it handles data currently? 

Thanks
Cieron

**Comment by acerix** [comment]
I'm sure there's a better way but I'm not familiar enough with Vue to know if it could be done in your demo or if that would need to be added as a new feature in this component.

**Comment by Cieronpowell** [comment]
Hi that’s fair enough, more than happy with that workaround, just wanted to make sure I wasn’t doing anything silly. I’m not an expert with  Vue / Vuex by any means, and only really play with this stuff as a hobby. From my understanding however the vuex store is designed to stop the need to pass data up and down the component tree via props and emitting events. So theoretically if FullCalendar were to work with vuex the component itself would use a getter on the store (like I’m doing in the demo outside the component) and then rather than emitting the event it would mutate the store to update the events (so no local events in memory). So kinda fundamentally different to how this works and don’t think you could get away with supporting vuex and native vue in a single interface.

One though that might make a workaround a little cleaner may be to have the event data emitted even when create:false is on the event, that way the event could be created by adding data to the store without duplicating locally, but I’m not sure if there is a specific reason this isn’t the case currently.

But like I said, the workaround you’ve provided works and is completely reasonable for my use case, just brainstorming potential “cleaner” solutions really

**Comment by paulyoung5** [comment]
I've also ran into this issue and did something similar to the workaround above, which works fine, a bit hacky I would agree

I guess this is more of a difference between how standard fullcalendar and fullcalendar-vue (and perhaps the other connectors) are used, as this behaviour makes sense for standard FullCalendar. 

for connector components, if the `events` prop is supposed to be the source of truth, in Vue I think this component might be better if emitting a Vue event called `event-created` or something, which would leave it up to the consuming code to update `events` prop with the newly-created event

**Comment by arshaw** [comment]
I'm sorry we can't help much, but @acerix and I are not very familiar with Vuex.

There are new developments with how an event store would work with React (if that's helpful at all). Please see [my latest comment](https://github.com/fullcalendar/fullcalendar-react/issues/65#issuecomment-644564521) on that issue.

There have been a number of improvements to FullCalendar's API in v5 to make this all easier.

What I'm hoping for is if [someone could help write a Vuex example](https://github.com/fullcalendar/fullcalendar-vue/issues/94), using the Redux example for inspiration.
