### ISSUE TITLE
rrule cant be seen in extendedProps

### ISSUE THREAD

**Issue by jkque** [fullcalendar/fullcalendar-vue#8]
https://codesandbox.io/s/4rvmz79p4w

In the console rrule object can't be seen in extendedProps when allDay is true
and in allDay false it cant be seen if startTime and endTime is not set

**Comment by acerix** [comment]
The 'rrule' object is not meant to be exposed, to request that as a new feature, please open a ticket in the main repo since it is not specific to the Vue component.

https://fullcalendar.io/requesting-features

https://github.com/fullcalendar/fullcalendar/issues/new
