### ISSUE TITLE
"Giant list of props and events" in docs link to src/fullcalendar-options.js is not found

### ISSUE THREAD

**Issue by ETSmukesh** [fullcalendar/fullcalendar-vue#82]
I'm accessing this page from vue-fullcalendar docs-> https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/fullcalendar-options.js but it's getting page not found.

**Comment by cyberkeiler** [comment]
Missing it, too ...

**Comment by acerix** [comment]
Thanks, confirmed.  The file is now in the v4 branch:

https://github.com/fullcalendar/fullcalendar-vue/blob/v4/src/fullcalendar-options.js

**Comment by arshaw** [comment]
this is now fixed on the live site. sorry about that

**Comment by ETSmukesh** [comment]
> this is now fixed on the live site. sorry about that

Thanks :)
