### ISSUE TITLE
[5.0.0-beta.3] Lots of compilation error (TypeScript related? vue-cli related?)

### ISSUE THREAD

**Issue by titou10titou10** [fullcalendar/fullcalendar-vue#85]
I was experimenting with Vue.js and fullcalender and timeline v4.4.0 and everything was working fine.
Now I just created another application with v5.0.0-beta.3 and I'm not able to compile my app.
Using Vue v2.6.11, vue-cli v4.3.1, TypeScript v3.9.3, fullcalendar v5.0.0-beta3...

Some of the errors:

    > tv-spa@0.1.0 build E:\spa\tv_spa\spa
    > vue-cli-service build --modern
    
    Starting type checking service...
    Using 1 worker with 2048MB memory limit
    ERROR  Failed to compile with 34 errors6:10:16 p.m.
    
    error  in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/main.d.ts
    
    ERROR in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/main.d.ts(531,66):
    531:66 Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.
      Property 'datesDidUpdate' is incompatible with index signature.
        Type '((arg: { view: ViewApi; }) => void) | undefined' is not assignable to type '(...args: any[]) => any'.
          Type 'undefined' is not assignable to type '(...args: any[]) => any'.
        529 |     private scrollTime;
        530 |     queuedRequest: ScrollRequest;
      > 531 |     constructor(execFunc: ScrollRequestHandler, emitter: Emitter<CalendarListeners>, scrollTime: Duration);
            |                                                                  ^
        532 |     detach(): void;
        533 |     update(isDatesNew: boolean): void;
        534 |     private fireInitialScroll;
    
     error  in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/main.d.ts
    
    ERROR in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/main.d.ts(860,22):
    860:22 Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.
        858 |     calendarApi: CalendarApi;
        859 |     dispatch: (action: Action) => void;
      > 860 |     emitter: Emitter<CalendarListeners>;
            |                      ^
        861 |     getCurrentData(): CalendarData;
        862 | }
        863 | 
    
    {...}
    
    ERROR in E:/spa/tv_spa/spa/node_modules/@fullcalendar/timeline/main.d.ts(3,23):
    3:23 Cannot find module './vdom' or its corresponding type declarations.
        1 | 
        2 | import { Duration, DateRange, DateMarker, DateProfile, DateEnv, BaseOptionsRefined, DateProfileGenerator, PositionCache, DateComponent, ViewProps, createElement, Seg, Slicer, EventStore, EventUiHash, DateSpan, EventInteractionState, BaseComponent, RefObject, CssDimValue, VNode as VNode$1, ScrollRequest, PluginDef } from '@fullcalendar/common';
      > 3 | import { VNode } from './vdom';
          |                       ^
        4 | 
        5 | interface TimelineDateProfile {
        6 |     labelInterval: Duration;

Extract of my package.json:

    {
      "dependencies": {
        "@fullcalendar/core": "^v5.0.0-beta.3",
        "@fullcalendar/interaction": "^v5.0.0-beta.3",
        "@fullcalendar/resource-timeline": "^v5.0.0-beta.3",
        "@fullcalendar/vue": "^v5.0.0-beta.3",
        "core-js": "^3.6.4",
        "moment": "^2.26.0",
        "vue": "^2.6.11",
        "vue-class-component": "^7.2.3",
        "vue-property-decorator": "^8.4.1",
        "vue-router": "^3.2.0",
        "vuetify": "^2.2.29",
        "vuex": "^3.1.3",
        "vuex-persistedstate": "^3.0.1"
      },
      "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^2.34.0",
        "@typescript-eslint/parser": "^2.34.0",
        "@vue/cli-plugin-babel": "~4.3.0",
        "@vue/cli-plugin-eslint": "~4.3.0",
        "@vue/cli-plugin-router": "~4.3.0",
        "@vue/cli-plugin-typescript": "~4.3.0",
        "@vue/cli-plugin-vuex": "~4.3.0",
        "@vue/cli-service": "~4.3.0",
        "@vue/eslint-config-prettier": "^6.0.0",
        "@vue/eslint-config-typescript": "^5.0.2",
        "axios": "^0.19.0",
        "eslint": "^6.7.2",
        "eslint-plugin-prettier": "^3.1.1",
        "eslint-plugin-vue": "^6.2.2",
        "prettier": "^1.19.1",
        "sass": "^1.26.3",
        "sass-loader": "^8.0.2",
        "typescript": "~3.9.3",
        "vue-cli-plugin-axios-ts": "~1.0.2",
        "vue-cli-plugin-vuetify": "~2.0.5",
        "vue-template-compiler": "^2.6.11",
        "vuetify-loader": "^1.3.0"
      }
    }

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

It may help to use the example project as a starting point:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/vue

**Comment by arshaw** [comment]
it could be that you still have the old typescript definitions present in the project (because you might have the old versions of FC installed side-by-side) and the definitions are conflicting. Could you try to clean your project including deleting node_modules, start over, and lmk if the errors are still present?

**Comment by titou10titou10** [comment]
@arshaw yes I did that before (ie delete node_modules + npm install etc) with the same result
What would be great is to have a FC sample project with Vue.js and TS as upcoming Vue.js v3 will be in TS. 
I will try to start from the sample Vue project https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/vue and introduce TS in it to see how it goes but I'm far from an expert with webpack etc

**Comment by acerix** [comment]
There is very similar issue in the main repo:

https://github.com/fullcalendar/fullcalendar/issues/5446

**Comment by arshaw** [comment]
hey @titou10titou10 , I fixed this in beta4. Could you please verify?

**Comment by titou10titou10** [comment]
@arshaw : Cool. I will test it tomorrow

**Comment by titou10titou10** [comment]
@arshaw your fix solves many compilation problems.
Now I have those errors. All are in `@fullcalendar/common/vdom.d.ts` and all are about `FullCalendarVDom`:

    > vue-cli-service build --modern

     error  in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/vdom.d.ts

    ERROR in E:/spa/tv_spa/spa/node_modules/@fullcalendar/common/vdom.d.ts(2,21):
    2:21 Cannot find name 'FullCalendarVDom'.
        1 | 
      > 2 | export import Ref = FullCalendarVDom.Ref;
      |                     ^
        3 | export import RefObject = FullCalendarVDom.RefObject;
        4 | export import ComponentType = FullCalendarVDom.ComponentType;
        5 | export import VNode = FullCalendarVDom.VNode;

**Comment by arshaw** [comment]
@titou10titou10 , i'm not exactly sure how vue-cli-service works, but for some reason @fullcalendar/core (which is imported buy @fullcalendar/vue) is not being loaded before @fullcalendar/common. @fullcalendar/core contains the `FullCalendarVDom` declarations that should be ambiently loaded.

When you write your import statements, did you write the vue statement before any plugins? like this:

```js
import FullCalendar from '@fullcalendar/vue'
import dayGridPlugin from '@fullcalendar/daygrid'
```

Any more information would be greatly appreciated. If you could somehow get reduce your code and get it into codepen, that'd be great.

**Comment by titou10titou10** [comment]
I didn't have any import for FC iun `main.ts` The`import`related to FC  where only in my views as I followed instructions [here](https://fullcalendar.io/docs/v5/vue).

I got it to work but I don't think what I've done is valid
In`main.ts`, if I add the following around the top, it works but I have an eslint  warning saying that `FullCalendar`is imported but never used...

    import FullCalendar from '@fullcalendar/core'

If I add the following, there is a compilation error saying `cannot find module @fullcalendar/vue`.

    import FullCalendar from '@fullcalendar/vue'
    Vue.component('FullCalendar', FullCalendar)  -> to mimic what has to be done for Primevue components

it is not easy to share my app, I will try to list the instructions to scaffold a basic project with vue-cli and TS later

**Comment by titou10titou10** [comment]
So here are the steps to scaffold a new app with vue-cli + TypeScript + FullCalendar and show the problem:

    npm install -g @vue/cli
    vue create test-fc

Choose:
- manually select features
- babel + typescript + router + vuex + css pre-processors + linter/formatter
- Use class-style component sysntx? Y
- Use Babel alongside TypeScript: Y
- Use history mode for router: Y
- Pick a CSS pre-processor: Saas/SCSS with dart-sass
- Pick a linter/formatter config: ESLint + Prettier
- Pick additional lint feature: Lint on save
- Where do you prefer placing config for Babel, ESLint, etc? In dedicated config files
- Save this a a preset: N

    cd test-fc

edit`package.json`, add under "dependencies"

     "dependencies": {
       "@fullcalendar/core": "^v5.0.0-beta.4",
       "@fullcalendar/interaction": "^v5.0.0-beta.4",
       "@fullcalendar/resource-timeline": "^v5.0.0-beta.4",
       "@fullcalendar/vue": "^v5.0.0-beta.4",
      {...}

Install/update packages

    npm update
    npm install

edit`views/Home.vue`
-> in`<template section>` add
   `<FullCalendar id="calendar" :options="calendarOptions" />`

-> in`<script>` section, add

    import FullCalendar from '@fullcalendar/vue'
    import interaction from '@fullcalendar/interaction'
    import resourceTimelinePlugin from '@fullcalendar/resource-timeline'
   
    export default {
     components: { HelloWorld, FullCalendar },
     data() {
     return {
       calendarOptions: {
         plugins: [interaction, resourceTimelinePlugin],
         scrollTime: '08:00',
         resourceAreaWidth: '10%',
         schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
         nowIndicator: true
       }

    npm run serve
    -> compile fail with "Cannot find namespace FullCalendar" as describe before

edit`main.ts`. add :

    import FullCalendar from '@fullcalendar/core';

Check server:
-> compile okay with a warning saying "FullCalendar" is defined but never used
   (could be hidden with an eslint directive)

-> app works: http://localhsot:8080
  ( with`Unknown option 'schedulerLicenseKey'`?)

Q: is adding`import FullCalendar from '@fullcalendar/core';`in main.ts the correct solution?

**Comment by arshaw** [comment]
@titou10titou10 thank you so much for all the detailed steps.

it would still be really appreciated to have a runnable example instead of needing to do all these steps manually.

any way you could work off of this code playground project?
https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/v5/vue?file=/src/DemoApp.vue

btw, the schedulerLicenseKey warning you're seeing is almost definitely related to this:
https://github.com/fullcalendar/fullcalendar/issues/5462
