### ISSUE TITLE
Calendar does not update when options change until it is re-rendered

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-vue#88]
With the v5 beta, the calendar seems to no longer update when any of the first-level options change.

Reproduction: https://codesandbox.io/s/fullcalendar-vue-16tdv

In the demo, I'm assigning `slotMinTime` to a different value, but the new value is not respected until a re-render is issued through other means, e.g. by navigating next/prev. This holds true both for a computed options object (which, afaik, would technically result in a new object being passed to fc when a value changes), and a static config object (which would be the same object, just with an updated property).

I did not observe any issue with updating events, if I e.g. pass an array to `events` and then add a new event to that array, the new event is rendered in the calendar. However this re-render does not cause the updated value for `slotMinTime` to apply.

**Comment by acerix** [comment]
Thanks, confirmed.  I believe it's a bug that it doesn't re-render automatically, it could be rendered manually as a workaround.

**Comment by arshaw** [comment]
note to self: has to do with computed properties

**Comment by arshaw** [comment]
fixed in the new [release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features). was actually a problem in one of the core packages.

https://codesandbox.io/s/fullcalendar-vue-jyb78?file=/index.html
