### ISSUE TITLE
Reactive Events?

### ISSUE THREAD

**Issue by bborn** [fullcalendar/fullcalendar-vue#9]
Any plans to make the events reactive (something along these lines: https://github.com/CroudTech/vue-fullcalendar/issues/7). It'd be cool to be able to modify the an event object and have the changes update on the calendar reactively, rather than having to remove and re-render the event.

**Comment by arshaw** [comment]
If the array of events is bound correctly to the fullcalendar component, then it should update when the events array updates. can you prove otherwise? with a [reduced test case](https://fullcalendar.io/reduced-test-cases) ?

**Comment by bborn** [comment]
Thanks ... I'll try it out when I have a moment. I'm using event sources, not an array of events.

**Comment by irongomme** [comment]
Hi

I've got no problem to have reactivity on events if they are in events attribute. 

But when I use eventSources witth nested events for each of them, unfortunately, I've got no reactivity when one event change, unless the whole source object change.

Is there a way to have reactivity on events in this kind of structure ?

**Comment by chrisribal** [comment]
I can also confirm that the events are not correctly updated. Adding and removing an event works, but changing any property of an event array (like the title for example) doesn't update the event in the calendar. Try my test case: https://codesandbox.io/embed/9o0r4lz5y

Just try to change the title in the table of the events. As you see, the title is not updated in the calendar.

Maybe we are required to set up a vue deep watch here? I'll try that and post my results asap.

**Comment by arshaw** [comment]
@irongomme could you post a reduced test case for the situation you describe with  `eventSources` ?

@chrisribal question, your demo doesn't seem to remove events, correct? also, i think i might know what's going on with it not updating event obj prop changes. i'll investigate for the next minor release.

**Comment by chrisribal** [comment]
@arshaw sorry, I've had a typo in my demo. Now you can remove the events without problems.

**Comment by arshaw** [comment]
thanks @chrisribal .

i see the bug with updating. i'm doing a comparison at a fixed depth to detect if there are changes and then rerender. I think i need to compare at one depth deeper. I'll fix this for the next version.

**Comment by arshaw** [comment]
this is now implemented in master! will release this very soon and comment on this ticket again

**Comment by arshaw** [comment]
in 4.2.0, the following props are now fully reactive: `events`, `eventSources`, `resources`, `header`, `footer`

https://github.com/fullcalendar/fullcalendar-vue/releases/tag/v4.2.0
