### ISSUE TITLE
eventContent / resourceLabelContent scoped slots not used after updating options

### ISSUE THREAD

**Issue by paulyoung5** [fullcalendar/fullcalendar-vue#91]
Firstly, v5 beta looks great, and for the Vue connector specifically, the new [scoped slots](https://github.com/fullcalendar/fullcalendar-vue/issues/14) are going to be _so_ useful, thanks very much for your hard work on this 🙏 

## Description

When passing `events` and `resources` arrays to the `options` prop, the events are rendered as expected using your scoped slot (i.e. `<template #eventContent>`).

However, when modifying `events` or `resources` dynamically (e.g. after an ajax call for events), it seems the events are rendered as if no scoped slot is present in the template.

## Reduced test case

This example is forked from the provided runnable demo.

### Expected behaviour

In this example, expected behaviour is that the event should read **"[Scoped slot was used]"** (it will be this way on loading the page).

### Actual behaviour

To reproduce the bug, un-comment the contents of the `mounted` hook, where we modify `this.events` and `this.resources`.

Actual behaviour now is that the event reads **"[Original Event Title]"**.

### Link

https://codesandbox.io/s/bug-when-setting-events-at-runtime-eventcontent-resourcelabelcontent-slots-not-used-1w3zy?file=/src/DemoApp.vue

--

It's very possible I am misunderstanding how these are supposed to work, let me know if any additional info or demos would be helpful.

Thanks in advance for your help!

**Comment by acerix** [comment]
Thanks for the report.  I'm not very familiar with how the scoped slots work, but can see in your demo that it uses that format initially but not after updating the event so that seems like a bug.

**Comment by arshaw** [comment]
fixed in the new [release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

https://codesandbox.io/s/bug-when-setting-events-on-the-fly-eventcontent-resourcelabelcontent-slots-not-used-wzvvm?file=/src/DemoApp.vue

**Comment by paulyoung5** [comment]
thanks very much @arshaw and @acerix 🙇
