### ISSUE TITLE
Callback for when date range changes

### ISSUE THREAD

**Issue by croossin** [fullcalendar/fullcalendar-vue#92]
Which event can we utilize to receive a callback when the date range changes? I don't see an event for viewRender

**Comment by arshaw** [comment]
in the latest v5 release candidate it's called [datesSet](https://fullcalendar.io/docs/v5/datesSet)

**Comment by mirlannur** [comment]
> in the latest v5 release candidate it's called [datesSet](https://fullcalendar.io/docs/v5/datesSet)
[datesSet](https://fullcalendar.io/docs/v5/datesSet) is not working 
[example code](https://github.com/fullcalendar/fullcalendar/issues/3521#issuecomment-766408159)

**Comment by nabeeltariqbhatti** [comment]
Dates Set is not working for me as well could anyone please help me about this?

**Comment by nabeeltariqbhatti** [comment]
dateSet:function(info) {
      alert('Clicked on: ' + info.start);
      alert("Clicked on"+ info.end);
  },

**Comment by nabeeltariqbhatti** [comment]
Its working fine now
