### ISSUE TITLE
Vuex Example

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-vue#94]
I've never used Vuex personally and I'd rather not spend time learning it while there is so much else to be done. An example project would be extremely useful for many people. Could someone help me out by writing one?

If someone could take the v5 [FullCalendar React+Redux example](https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/react-redux) and use the same concepts, functionality, and styling, **that'd be incredible!**

**Comment by paulyoung5** [comment]
hey @arshaw I've made a wee `vue-vuex` example using FullCalendar v5, Vue and Vuex here: fullcalendar/fullcalendar-example-projects#14

when you have time, would you be able to let me know if you have any thoughts please?

**Comment by arshaw** [comment]
thank you @paulyoung5 

https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/vue-vuex
